// Code generated by goyacc -v /tmp/y.output -o y.go grammar.y. DO NOT EDIT.

//line grammar.y:2
package ast

import __yyfmt__ "fmt"

//line grammar.y:2

//line grammar.y:45
type yySymType struct {
	yys                        int
	token                      Token
	stmt_if                    *IfStatement
	opt_elseif_list            Statements
	opt_else                   Statements
	stmt                       Statement
	stmt_loop                  *LoopStatement
	funcProc                   *FunctionOrProcedure
	body                       Statements
	opt_body                   Statements
	declarations_method_params []ParamStatement
	declarations_method_param  ParamStatement
	exprs                      ExprStatements
	opt_export                 *Token
	explicit_variables         map[string]VarStatement
	global_variables           []GlobalVariables
	opt_explicit_variables     map[string]VarStatement
	identifiers                []Token
	goToLabel                  *GoToLabelStatement
	opt_goToLabel              *GoToLabelStatement
	directive                  *DirectiveStatement
	directives                 []*DirectiveStatement
}

const Directive = 57346
const ExtDirective = 57347
const token_identifier = 57348
const Procedure = 57349
const Var = 57350
const EndProcedure = 57351
const If = 57352
const Then = 57353
const ElseIf = 57354
const Else = 57355
const EndIf = 57356
const For = 57357
const Each = 57358
const In = 57359
const To = 57360
const Loop = 57361
const EndLoop = 57362
const Break = 57363
const Not = 57364
const ValueParam = 57365
const While = 57366
const GoToLabel = 57367
const Continue = 57368
const Try = 57369
const Catch = 57370
const EndTry = 57371
const Number = 57372
const String = 57373
const New = 57374
const Function = 57375
const EndFunction = 57376
const Return = 57377
const Throw = 57378
const NeEQ = 57379
const EQUAL = 57380
const LE = 57381
const GE = 57382
const OR = 57383
const And = 57384
const True = 57385
const False = 57386
const Undefined = 57387
const Export = 57388
const Date = 57389
const GoTo = 57390
const Execute = 57391
const LOW_PREC = 57392
const UNARMinus = 57393
const UNARYPlus = 57394

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"':'",
	"';'",
	"','",
	"Directive",
	"ExtDirective",
	"token_identifier",
	"Procedure",
	"Var",
	"EndProcedure",
	"If",
	"Then",
	"ElseIf",
	"Else",
	"EndIf",
	"For",
	"Each",
	"In",
	"To",
	"Loop",
	"EndLoop",
	"Break",
	"Not",
	"ValueParam",
	"While",
	"GoToLabel",
	"Continue",
	"Try",
	"Catch",
	"EndTry",
	"Number",
	"String",
	"New",
	"Function",
	"EndFunction",
	"Return",
	"Throw",
	"NeEQ",
	"EQUAL",
	"LE",
	"GE",
	"OR",
	"And",
	"True",
	"False",
	"Undefined",
	"Export",
	"Date",
	"GoTo",
	"Execute",
	"LOW_PREC",
	"'>'",
	"'<'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARMinus",
	"UNARYPlus",
	"'('",
	"')'",
	"'?'",
	"'['",
	"']'",
	"'.'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line grammar.y:397

//line yacctab:1
var yyExca = [...]int8{
	-1, 0,
	1, 1,
	10, 14,
	11, 10,
	36, 14,
	-2, 22,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 2,
	-2, 23,
	-1, 3,
	10, 14,
	11, 10,
	36, 14,
	-2, 22,
	-1, 44,
	11, 11,
	-2, 12,
}

const yyPrivate = 57344

const yyLast = 639

var yyAct = [...]uint8{
	75, 7, 128, 121, 7, 5, 156, 53, 204, 49,
	19, 8, 22, 168, 24, 145, 169, 78, 59, 57,
	77, 193, 155, 149, 148, 79, 74, 74, 122, 7,
	122, 134, 74, 80, 86, 101, 99, 82, 84, 85,
	73, 76, 70, 67, 71, 72, 59, 95, 96, 97,
	90, 122, 4, 7, 122, 122, 65, 66, 60, 61,
	62, 63, 64, 122, 31, 62, 63, 64, 18, 104,
	147, 31, 106, 107, 108, 109, 110, 111, 112, 113,
	114, 115, 116, 117, 118, 122, 187, 185, 183, 119,
	42, 65, 66, 60, 61, 62, 63, 64, 56, 55,
	42, 94, 74, 98, 133, 103, 137, 32, 132, 173,
	74, 136, 153, 150, 32, 89, 135, 46, 161, 44,
	43, 120, 170, 189, 7, 178, 93, 105, 147, 140,
	141, 218, 146, 74, 56, 55, 176, 142, 212, 171,
	154, 88, 159, 206, 7, 7, 74, 139, 87, 164,
	165, 41, 152, 166, 160, 92, 162, 60, 61, 62,
	63, 64, 182, 172, 129, 100, 174, 56, 55, 177,
	56, 55, 184, 186, 179, 81, 184, 7, 188, 56,
	55, 7, 190, 56, 55, 167, 194, 56, 55, 209,
	157, 131, 7, 7, 127, 130, 197, 200, 201, 195,
	199, 196, 202, 198, 124, 7, 181, 208, 55, 213,
	211, 7, 210, 47, 48, 216, 214, 146, 55, 122,
	146, 217, 51, 2, 219, 47, 48, 31, 144, 56,
	55, 25, 56, 55, 6, 58, 26, 215, 50, 143,
	180, 192, 13, 21, 203, 27, 46, 12, 28, 3,
	1, 34, 33, 42, 30, 45, 15, 14, 29, 16,
	54, 52, 11, 205, 37, 38, 40, 158, 39, 23,
	32, 91, 102, 31, 36, 35, 175, 25, 9, 17,
	10, 20, 26, 43, 0, 0, 0, 0, 13, 21,
	0, 27, 46, 12, 28, 0, 0, 34, 33, 42,
	0, 0, 15, 14, 0, 0, 0, 31, 0, 0,
	37, 38, 40, 0, 39, 23, 32, 83, 0, 0,
	36, 35, 0, 21, 0, 0, 46, 20, 0, 43,
	0, 34, 33, 42, 0, 0, 0, 0, 0, 0,
	31, 0, 0, 0, 37, 38, 40, 0, 39, 23,
	32, 0, 0, 0, 36, 35, 21, 67, 0, 46,
	0, 20, 0, 43, 34, 33, 42, 0, 0, 0,
	65, 66, 60, 61, 62, 63, 64, 37, 38, 40,
	0, 39, 23, 32, 0, 0, 0, 36, 35, 0,
	70, 67, 71, 72, 20, 69, 43, 70, 67, 71,
	72, 68, 69, 0, 65, 66, 60, 61, 62, 63,
	64, 65, 66, 60, 61, 62, 63, 64, 70, 67,
	71, 72, 68, 69, 138, 0, 0, 0, 0, 0,
	0, 0, 65, 66, 60, 61, 62, 63, 64, 0,
	0, 0, 207, 70, 67, 71, 72, 68, 69, 191,
	163, 0, 0, 0, 0, 0, 0, 65, 66, 60,
	61, 62, 63, 64, 122, 0, 0, 151, 70, 67,
	71, 72, 68, 69, 0, 70, 67, 71, 72, 68,
	69, 0, 65, 66, 60, 61, 62, 63, 64, 65,
	66, 60, 61, 62, 63, 64, 0, 0, 70, 67,
	71, 72, 68, 69, 126, 0, 0, 0, 0, 0,
	125, 0, 65, 66, 60, 61, 62, 63, 64, 0,
	0, 0, 70, 67, 71, 72, 68, 69, 123, 70,
	67, 71, 72, 68, 69, 0, 65, 66, 60, 61,
	62, 63, 64, 65, 66, 60, 61, 62, 63, 64,
	0, 0, 0, 0, 70, 67, 71, 72, 68, 69,
	0, 70, 67, 71, 72, 68, 69, 0, 65, 66,
	60, 61, 62, 63, 64, 65, 66, 60, 61, 62,
	63, 64, 67, 71, 72, 0, 0, 0, 0, 67,
	0, 72, 0, 0, 0, 65, 66, 60, 61, 62,
	63, 64, 65, 66, 60, 61, 62, 63, 64, 46,
	0, 0, 0, 0, 34, 33, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 37, 38, 40,
	0, 39, 0, 0, 0, 0, 0, 36, 35,
}

var yyPact = [...]int16{
	218, -1000, -1000, 218, -1000, 228, -1000, -22, 521, -1000,
	-1000, -1000, -1000, -1000, 331, 331, -1000, -1000, -46, -1000,
	331, 331, -1000, 89, -1000, 331, 298, 331, 264, 137,
	105, -13, 92, -1000, -1000, 331, 331, -1000, -1000, -1000,
	-1000, -1000, 40, -27, -1000, 206, -1000, -1000, -28, 228,
	-1000, -1000, 264, -1000, -1000, -1000, -1000, 331, 62, -1000,
	331, 331, 331, 331, 331, 331, 331, 331, 331, 331,
	331, 331, 331, -1000, 521, -50, -1000, 331, 57, -1000,
	316, -1000, 514, 195, 489, 482, 163, 155, 186, 182,
	331, -1000, 331, -1000, -1000, -1000, -1000, -32, 331, 331,
	-1000, 72, -1000, -1000, 521, -46, 7, 7, -1000, -1000,
	-1000, 101, 101, 37, 350, 2, 541, 548, 316, 357,
	-1000, 331, -1000, 264, 110, 331, -1000, -1000, 79, -1000,
	-39, -40, 49, 403, 331, 48, 458, -42, -1000, -1000,
	175, 55, 428, 264, 264, 203, 176, -1000, 113, 113,
	-1000, -1000, 45, -1000, 331, -1000, 120, 331, 103, -50,
	-1000, 65, -1000, -1000, 183, 130, -1000, -1000, 24, 46,
	-1000, 164, 22, -1000, 458, 106, 264, 435, -1000, -43,
	264, -1000, -1000, 21, 113, 581, -1000, 21, 331, -1000,
	228, 264, 264, -1000, 179, -1000, 46, -1000, 132, 378,
	175, 166, -1000, 132, 264, 127, 155, -1000, -1000, -1000,
	264, 225, 155, 213, 94, -1000, 213, -1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 222, 5, 52, 280, 279, 278, 6, 276, 272,
	17, 11, 15, 10, 13, 16, 25, 271, 0, 267,
	12, 14, 8, 263, 2, 262, 68, 151, 261, 7,
	260, 259, 3, 119, 258, 255, 254, 250, 249, 234,
	244, 241, 240, 239, 235, 228,
}

var yyR1 = [...]int8{
	0, 37, 37, 37, 38, 38, 39, 39, 33, 33,
	34, 34, 35, 35, 36, 36, 12, 12, 31, 40,
	5, 5, 2, 2, 1, 1, 9, 9, 28, 28,
	22, 22, 23, 23, 6, 7, 7, 8, 8, 21,
	41, 4, 42, 4, 43, 4, 19, 19, 19, 19,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 18,
	18, 26, 26, 26, 26, 26, 17, 17, 45, 25,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	16, 16, 10, 10, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 15, 15, 15, 14, 14, 14, 20,
	20, 20, 27, 24, 24, 29, 30, 32, 44,
}

var yyR2 = [...]int8{
	0, 0, 1, 2, 1, 2, 1, 1, 1, 4,
	0, 1, 1, 2, 0, 1, 0, 1, 5, 0,
	11, 10, 0, 1, 1, 3, 0, 1, 1, 1,
	0, 1, 3, 4, 7, 0, 5, 0, 2, 8,
	0, 9, 0, 8, 0, 6, 1, 1, 3, 1,
	3, 1, 1, 1, 1, 1, 1, 2, 2, 1,
	3, 1, 4, 4, 2, 4, 1, 1, 0, 6,
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 2, 1, 2, 1, 1,
	0, 1, 1, 3, 1, 1, 2, 2, 1, 1,
	1, 1, 1, 1, 2, 3, 0, 1, 3, 2,
	5, 4, 1, 1, 3, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -37, -1, -38, -3, -2, -39, -18, -11, -6,
	-4, -25, 29, 24, 39, 38, -31, -5, -26, -13,
	63, 25, -20, 51, -21, 13, 18, 27, 30, -34,
	-36, 9, 52, 34, 33, 57, 56, 46, 47, 50,
	48, -27, 35, 65, -33, -35, 28, 7, 8, -2,
	-39, -1, -28, -29, -30, 5, 4, 41, -44, 68,
	56, 57, 58, 59, 60, 54, 55, 41, 44, 45,
	40, 42, 43, -16, -11, -18, -16, 66, -10, -16,
	-11, -27, -11, 19, -11, -11, -2, 11, 36, 10,
	63, -17, 63, 34, 9, -11, -11, 9, 63, 63,
	-33, 63, -9, -3, -11, -26, -11, -11, -11, -11,
	-11, -11, -11, -11, -11, -11, -11, -11, -11, -11,
	64, -32, 6, 14, 9, 21, 22, 31, -24, 9,
	9, 9, -10, -11, 63, -10, -11, 34, 67, -16,
	-2, 20, -11, -43, -45, -12, -32, 49, 63, 63,
	64, 64, -10, 64, -32, 64, -7, 15, -19, -18,
	-20, 63, -21, 22, -2, -2, -29, 9, -14, -15,
	9, 26, -14, 64, -11, -8, 16, -11, 22, -20,
	-42, 23, 32, 64, -32, 41, 9, 64, -32, 17,
	-2, 14, -41, 64, -2, -12, -15, -13, -12, -11,
	-2, -2, 23, -40, -22, -23, 11, 64, -7, 23,
	-22, -2, 11, -24, -2, 12, -24, -29, 37, -29,
}

var yyDef = [...]int8{
	-2, -2, -2, -2, 24, 0, 4, 89, 51, 52,
	53, 54, 55, 56, 90, 90, 6, 7, 59, 70,
	90, 0, 86, 0, 88, 0, 0, 0, 22, 0,
	0, 61, 0, 94, 95, 0, 0, 98, 99, 100,
	101, 102, 0, 0, -2, 15, 112, 8, 0, 3,
	5, 23, 26, 28, 29, 115, 116, 0, 0, 118,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 57, 91, 89, 58, 0, 0, 92,
	85, 87, 0, 0, 0, 0, 0, 0, 0, 0,
	90, 64, 0, 66, 67, 96, 97, 109, 90, 0,
	13, 0, 25, 27, 50, 60, 72, 73, 74, 75,
	76, 77, 78, 79, 80, 81, 82, 83, 84, 0,
	71, 90, 117, 22, 0, 0, 44, 68, 16, 113,
	0, 0, 0, 0, 90, 0, 0, 0, 63, 93,
	35, 0, 0, 22, 22, 0, 0, 17, 106, 106,
	62, 65, 0, 111, 0, 9, 37, 0, 0, 46,
	47, 0, 49, 42, 0, 0, 18, 114, 0, 107,
	103, 0, 0, 110, 0, 0, 22, 0, 40, 0,
	22, 45, 69, 16, 0, 0, 104, 16, 0, 34,
	38, 22, 22, 48, 0, 19, 108, 105, 30, 0,
	35, 0, 43, 30, 22, 31, 0, 39, 36, 41,
	22, 0, 0, 0, 0, 21, 0, 32, 20, 33,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 60, 3, 3,
	63, 64, 58, 56, 6, 57, 68, 59, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 5,
	55, 3, 54, 65, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 66, 3, 67,
}

var yyTok2 = [...]int8{
	2, 3, 7, 8, 9, 10, 11, 12, 13, 14,
	15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
	35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
	45, 46, 47, 48, 49, 50, 51, 52, 53, 61,
	62,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:88
		{
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:89
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].body, yylex)
			}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:94
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[2].opt_body, yylex)
			}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:104
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].global_variables, yylex)
			}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:109
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].funcProc, yylex)
			}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:118
		{
			yyVAL.directive = &DirectiveStatement{Name: yyDollar[1].token.literal}
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:119
		{
			yyVAL.directive = &DirectiveStatement{Name: yyDollar[1].token.literal, Src: yyDollar[3].token.literal}
		}
	case 10:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:122
		{
			yyVAL.directive = nil
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:123
		{
			yyVAL.directive = yyDollar[1].directive
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:126
		{
			yyVAL.directives = []*DirectiveStatement{yyDollar[1].directive}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:127
		{
			yyVAL.directives = append(yyVAL.directives, yyDollar[2].directive)
		}
	case 14:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:130
		{
			yyVAL.directives = nil
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:131
		{
			yyVAL.directives = yyDollar[1].directives
		}
	case 16:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:134
		{
			yyVAL.opt_export = nil
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:135
		{
			yyVAL.opt_export = &yyDollar[1].token
		}
	case 18:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:138
		{
			yyVAL.global_variables = make([]GlobalVariables, len(yyDollar[3].identifiers), len(yyDollar[3].identifiers))
			for i, v := range yyDollar[3].identifiers {
				if yyDollar[1].directive != nil {
					yyVAL.global_variables[i].Directive = yyDollar[1].directive
				}

				yyVAL.global_variables[i].Export = yyDollar[4].opt_export != nil
				yyVAL.global_variables[i].Var = VarStatement{Name: v.literal}
			}
		}
	case 19:
		yyDollar = yyS[yypt-7 : yypt+1]
//line grammar.y:151
		{
			isFunction(true, yylex)
		}
	case 20:
		yyDollar = yyS[yypt-11 : yypt+1]
//line grammar.y:152
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeFunction, yyDollar[1].directives, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[9].opt_explicit_variables, yyDollar[10].opt_body)
			isFunction(false, yylex)
		}
	case 21:
		yyDollar = yyS[yypt-10 : yypt+1]
//line grammar.y:157
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeProcedure, yyDollar[1].directives, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[8].opt_explicit_variables, yyDollar[9].opt_body)
		}
	case 22:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:162
		{
			yyVAL.opt_body = nil
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:163
		{
			yyVAL.opt_body = yyDollar[1].body
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:167
		{
			yyVAL.body = Statements{yyDollar[1].stmt}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:168
		{
			if yyDollar[2].token.literal == ":" && len(yyDollar[1].opt_body) > 0 {
				if _, ok := yyDollar[1].opt_body[len(yyDollar[1].opt_body)-1].(*GoToLabelStatement); !ok {
					yylex.Error("semicolon (;) is expected")
				}
			}
			if yyDollar[3].stmt != nil {
				yyVAL.body = append(yyVAL.body, yyDollar[3].stmt)
			}
		}
	case 26:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:181
		{
			yyVAL.stmt = nil
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:182
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:185
		{
			yyVAL.token = yyDollar[1].token
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:185
		{
			yyVAL.token = yyDollar[1].token
		}
	case 30:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:189
		{
			yyVAL.opt_explicit_variables = map[string]VarStatement{}
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:190
		{
			yyVAL.opt_explicit_variables = yyDollar[1].explicit_variables
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:193
		{
			if vars, err := appendVarStatements(map[string]VarStatement{}, yyDollar[2].identifiers); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.explicit_variables = vars
			}
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:200
		{
			if vars, err := appendVarStatements(yyDollar[1].explicit_variables, yyDollar[3].identifiers); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.explicit_variables = vars
			}
		}
	case 34:
		yyDollar = yyS[yypt-7 : yypt+1]
//line grammar.y:211
		{
			yyVAL.stmt_if = &IfStatement{
				Expression:  yyDollar[2].stmt,
				TrueBlock:   yyDollar[4].opt_body,
				IfElseBlock: yyDollar[5].opt_elseif_list,
				ElseBlock:   yyDollar[6].opt_else,
			}
		}
	case 35:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:221
		{
			yyVAL.opt_elseif_list = Statements{}
		}
	case 36:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:222
		{
			yyVAL.opt_elseif_list = append(yyDollar[5].opt_elseif_list, &IfStatement{
				Expression: yyDollar[2].stmt,
				TrueBlock:  yyDollar[4].opt_body,
			})
		}
	case 37:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:230
		{
			yyVAL.opt_else = nil
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:231
		{
			yyVAL.opt_else = yyDollar[2].opt_body
		}
	case 39:
		yyDollar = yyS[yypt-8 : yypt+1]
//line grammar.y:234
		{
			yyVAL.stmt = TernaryStatement{
				Expression: yyDollar[3].stmt,
				TrueBlock:  yyDollar[5].stmt,
				ElseBlock:  yyDollar[7].stmt,
			}
		}
	case 40:
		yyDollar = yyS[yypt-6 : yypt+1]
//line grammar.y:243
		{
			setLoopFlag(true, yylex)
		}
	case 41:
		yyDollar = yyS[yypt-9 : yypt+1]
//line grammar.y:243
		{
			yyVAL.stmt_loop = &LoopStatement{
				For:  yyDollar[3].token.literal,
				In:   yyDollar[5].stmt,
				Body: yyDollar[8].opt_body,
			}
			setLoopFlag(false, yylex)
		}
	case 42:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:251
		{
			setLoopFlag(true, yylex)
		}
	case 43:
		yyDollar = yyS[yypt-8 : yypt+1]
//line grammar.y:251
		{
			yyVAL.stmt_loop = &LoopStatement{
				For:  yyDollar[2].stmt,
				To:   yyDollar[4].stmt,
				Body: yyDollar[7].opt_body,
			}
			setLoopFlag(false, yylex)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:259
		{
			setLoopFlag(true, yylex)
		}
	case 45:
		yyDollar = yyS[yypt-6 : yypt+1]
//line grammar.y:259
		{
			yyVAL.stmt_loop = &LoopStatement{
				WhileExpr: yyDollar[2].stmt,
				Body:      yyDollar[5].opt_body,
			}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:268
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:269
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:270
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:271
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:275
		{
			v := yyDollar[1].stmt
			if tok, ok := yyDollar[1].stmt.(Token); ok {
				v = VarStatement{Name: tok.literal}
			}
			yyVAL.stmt = AssignmentStatement{Var: v, Expr: ExprStatements{Statements: Statements{yyDollar[3].stmt}}}
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:282
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:283
		{
			yyVAL.stmt = yyDollar[1].stmt_if
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:284
		{
			yyVAL.stmt = yyDollar[1].stmt_loop
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:285
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:286
		{
			yyVAL.stmt = ContinueStatement{}
			checkLoopOperator(yyDollar[1].token, yylex)
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:287
		{
			yyVAL.stmt = BreakStatement{}
			checkLoopOperator(yyDollar[1].token, yylex)
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:288
		{
			yyVAL.stmt = ThrowStatement{Param: yyDollar[2].stmt}
			checkThrowParam(yyDollar[1].token, yyDollar[2].stmt, yylex)
		}
	case 58:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:289
		{
			yyVAL.stmt = &ReturnStatement{Param: yyDollar[2].stmt}
			checkReturnParam(yyDollar[2].stmt, yylex)
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:294
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:295
		{
			yyVAL.stmt = CallChainStatement{Unit: yyDollar[3].stmt, Call: yyDollar[1].stmt}
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:301
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:302
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: yyDollar[3].exprs}
		}
	case 63:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:303
		{
			yyVAL.stmt = ItemStatement{Object: yyDollar[1].stmt, Item: yyDollar[3].stmt}
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:304
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[2].stmt}}}
		}
	case 65:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:305
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[3].stmt}}}
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:308
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:309
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:312
		{
			setTryFlag(true, yylex)
		}
	case 69:
		yyDollar = yyS[yypt-6 : yypt+1]
//line grammar.y:312
		{
			yyVAL.stmt = TryStatement{Body: yyDollar[2].opt_body, Catch: yyDollar[5].opt_body}
			setTryFlag(false, yylex)
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:318
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:319
		{
			yyVAL.stmt = yyDollar[2].exprs
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:320
		{
			yyVAL.stmt = &ExpStatement{Operation: OpPlus, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:321
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMinus, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:322
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMul, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:323
		{
			yyVAL.stmt = &ExpStatement{Operation: OpDiv, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:324
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMod, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:325
		{
			yyVAL.stmt = &ExpStatement{Operation: OpGt, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:326
		{
			yyVAL.stmt = &ExpStatement{Operation: OpLt, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:327
		{
			yyVAL.stmt = &ExpStatement{Operation: OpEq, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:328
		{
			yyVAL.stmt = &ExpStatement{Operation: OpOr, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:329
		{
			yyVAL.stmt = &ExpStatement{Operation: OpAnd, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:330
		{
			yyVAL.stmt = &ExpStatement{Operation: OpNe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:331
		{
			yyVAL.stmt = &ExpStatement{Operation: OpLe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:332
		{
			yyVAL.stmt = &ExpStatement{Operation: OpGe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:333
		{
			yyVAL.stmt = not(yyDollar[2].stmt)
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:334
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:335
		{
			yyVAL.stmt = GoToStatement{Label: yyDollar[2].goToLabel}
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:336
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:337
		{
			if tok, ok := yyDollar[1].stmt.(Token); ok {
				yyVAL.stmt = tok.literal
			} else {
				yyVAL.stmt = yyDollar[1].stmt
			}
		}
	case 90:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:346
		{
			yyVAL.stmt = nil
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:346
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:348
		{
			yyVAL.exprs = ExprStatements{Statements: Statements{yyDollar[1].stmt}}
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:349
		{
			yyVAL.exprs.Statements = append(yyVAL.exprs.Statements, yyDollar[3].stmt)
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:352
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:353
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 96:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:354
		{
			yyVAL.stmt = unaryMinus(yyDollar[2].stmt)
		}
	case 97:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:355
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:356
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:357
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:358
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:359
		{
			yyVAL.stmt = UndefinedStatement{}
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:360
		{
			yyVAL.stmt = yyDollar[1].goToLabel
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:364
		{
			yyVAL.declarations_method_param = *(&ParamStatement{}).Fill(nil, yyDollar[1].token)
		}
	case 104:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:365
		{
			yyVAL.declarations_method_param = *(&ParamStatement{}).Fill(&yyDollar[1].token, yyDollar[2].token)
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:366
		{
			yyVAL.declarations_method_param = *(yyVAL.declarations_method_param.DefaultValue(yyDollar[3].stmt))
		}
	case 106:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:369
		{
			yyVAL.declarations_method_params = []ParamStatement{}
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:370
		{
			yyVAL.declarations_method_params = []ParamStatement{yyDollar[1].declarations_method_param}
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:371
		{
			yyVAL.declarations_method_params = append(yyDollar[1].declarations_method_params, yyDollar[3].declarations_method_param)
		}
	case 109:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:379
		{
			yyVAL.stmt = NewObjectStatement{Constructor: yyDollar[2].token.literal}
		}
	case 110:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:380
		{
			yyVAL.stmt = NewObjectStatement{Constructor: yyDollar[2].token.literal, Param: yyDollar[4].exprs}
		}
	case 111:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:381
		{
			yyVAL.stmt = NewObjectStatement{Param: yyDollar[3].exprs}
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:386
		{
			yyVAL.goToLabel = &GoToLabelStatement{Name: yyDollar[1].token.literal}
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:388
		{
			yyVAL.identifiers = []Token{yyDollar[1].token}
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:389
		{
			yyVAL.identifiers = append(yyVAL.identifiers, yyDollar[3].token)
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:392
		{
			yyVAL.token = yyDollar[1].token
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:393
		{
			yyVAL.token = yyDollar[1].token
		}
	case 117:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:394
		{
			yyVAL.token = yyDollar[1].token
		}
	}
	goto yystack /* stack new state and value */
}
