// Code generated by goyacc -o ast/y.go ast/grammar.y. DO NOT EDIT.

//line ast/grammar.y:2
package ast

import __yyfmt__ "fmt"

//line ast/grammar.y:2

//line ast/grammar.y:53
type yySymType struct {
	yys                        int
	token                      Token
	stmt_if                    *IfStatement
	opt_elseif_list            Statements
	opt_else                   Statements
	stmt                       Statement
	stmt_loop                  *LoopStatement
	funcProc                   *FunctionOrProcedure
	body                       Statements
	opt_body                   Statements
	declarations_method_params []ParamStatement
	declarations_method_param  ParamStatement
	exprs                      ExprStatements
	opt_export                 *Token
	explicit_variables         map[string]VarStatement
	global_variables           []GlobalVariables
	opt_explicit_variables     map[string]VarStatement
	identifiers                []Token
	goToLabel                  *GoToLabelStatement
	opt_goToLabel              *GoToLabelStatement
	directive                  *DirectiveStatement
	directives                 []*DirectiveStatement
	preproc_if                 *PreprocessorIfStatement
	preproc_elseifs            []PreprocessorElseIf
	preproc_body               Statements
	region_stmt                *RegionStatement
	use_stmt                   *UseStatement
}

const Directive = 57346
const ExtDirective = 57347
const token_identifier = 57348
const Procedure = 57349
const Var = 57350
const EndProcedure = 57351
const If = 57352
const Then = 57353
const ElseIf = 57354
const Else = 57355
const EndIf = 57356
const For = 57357
const Each = 57358
const In = 57359
const To = 57360
const Loop = 57361
const EndLoop = 57362
const Break = 57363
const Not = 57364
const ValueParam = 57365
const While = 57366
const GoToLabel = 57367
const Continue = 57368
const Try = 57369
const Catch = 57370
const EndTry = 57371
const Number = 57372
const String = 57373
const New = 57374
const Function = 57375
const EndFunction = 57376
const Return = 57377
const Throw = 57378
const NeEQ = 57379
const EQUAL = 57380
const LE = 57381
const GE = 57382
const OR = 57383
const And = 57384
const True = 57385
const False = 57386
const Undefined = 57387
const Null = 57388
const Export = 57389
const Date = 57390
const GoTo = 57391
const Execute = 57392
const Async = 57393
const Await = 57394
const LVALUE_IDENT = 57395
const CALL_IDENT = 57396
const PreprocIf = 57397
const PreprocElseIf = 57398
const PreprocElse = 57399
const PreprocEndIf = 57400
const PreprocRegion = 57401
const PreprocEndRegion = 57402
const PreprocUse = 57403
const LOW_PREC = 57404
const UNARMinus = 57405
const UNARYPlus = 57406

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"':'",
	"';'",
	"','",
	"Directive",
	"ExtDirective",
	"token_identifier",
	"Procedure",
	"Var",
	"EndProcedure",
	"If",
	"Then",
	"ElseIf",
	"Else",
	"EndIf",
	"For",
	"Each",
	"In",
	"To",
	"Loop",
	"EndLoop",
	"Break",
	"Not",
	"ValueParam",
	"While",
	"GoToLabel",
	"Continue",
	"Try",
	"Catch",
	"EndTry",
	"Number",
	"String",
	"New",
	"Function",
	"EndFunction",
	"Return",
	"Throw",
	"NeEQ",
	"EQUAL",
	"LE",
	"GE",
	"OR",
	"And",
	"True",
	"False",
	"Undefined",
	"Null",
	"Export",
	"Date",
	"GoTo",
	"Execute",
	"Async",
	"Await",
	"LVALUE_IDENT",
	"CALL_IDENT",
	"PreprocIf",
	"PreprocElseIf",
	"PreprocElse",
	"PreprocEndIf",
	"PreprocRegion",
	"PreprocEndRegion",
	"PreprocUse",
	"LOW_PREC",
	"'>'",
	"'<'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARMinus",
	"UNARYPlus",
	"'('",
	"')'",
	"'?'",
	"'.'",
	"'['",
	"']'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line ast/grammar.y:602

//line yacctab:1
var yyExca = [...]int16{
	-1, 0,
	1, 1,
	11, 13,
	-2, 32,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 2,
	-2, 33,
	-1, 3,
	11, 13,
	-2, 32,
	-1, 34,
	11, 13,
	-2, 102,
	-1, 35,
	63, 102,
	-2, 13,
	-1, 37,
	11, 14,
	-2, 15,
	-1, 101,
	11, 13,
	-2, 103,
	-1, 219,
	11, 13,
	-2, 102,
	-1, 220,
	61, 102,
	-2, 13,
}

const yyPrivate = 57344

const yyLast = 831

var yyAct = [...]int16{
	74, 18, 154, 5, 18, 233, 57, 40, 208, 52,
	207, 44, 61, 56, 246, 51, 4, 115, 85, 102,
	78, 77, 63, 64, 53, 54, 100, 116, 18, 114,
	50, 90, 144, 53, 54, 18, 18, 138, 86, 88,
	89, 296, 55, 80, 18, 81, 75, 287, 221, 174,
	251, 105, 105, 125, 126, 120, 121, 122, 123, 124,
	111, 117, 108, 136, 79, 84, 112, 113, 119, 250,
	222, 216, 215, 134, 135, 214, 133, 130, 127, 131,
	132, 139, 140, 211, 204, 127, 238, 132, 76, 192,
	83, 175, 174, 163, 174, 156, 148, 174, 174, 145,
	174, 174, 18, 125, 126, 120, 121, 122, 123, 124,
	125, 126, 120, 121, 122, 123, 124, 166, 105, 292,
	174, 165, 174, 143, 174, 146, 174, 170, 171, 174,
	173, 147, 174, 109, 177, 178, 179, 180, 181, 182,
	183, 184, 185, 186, 187, 188, 189, 174, 173, 174,
	18, 256, 167, 199, 127, 131, 132, 194, 195, 191,
	193, 197, 291, 196, 281, 201, 84, 279, 278, 205,
	277, 274, 141, 247, 217, 122, 123, 124, 206, 125,
	126, 120, 121, 122, 123, 124, 219, 220, 224, 78,
	261, 83, 260, 226, 255, 174, 245, 47, 46, 231,
	75, 225, 228, 18, 18, 159, 241, 242, 173, 229,
	227, 173, 168, 237, 28, 283, 243, 190, 98, 172,
	18, 18, 249, 239, 236, 252, 253, 254, 209, 266,
	338, 158, 82, 79, 117, 37, 105, 105, 142, 206,
	259, 173, 173, 262, 97, 210, 257, 258, 265, 47,
	46, 267, 200, 127, 273, 272, 120, 121, 122, 123,
	124, 275, 276, 47, 46, 18, 264, 93, 284, 18,
	38, 39, 288, 96, 173, 298, 153, 282, 125, 126,
	120, 121, 122, 123, 124, 311, 18, 18, 91, 300,
	301, 270, 155, 47, 46, 248, 299, 18, 203, 94,
	310, 312, 244, 213, 18, 212, 314, 316, 18, 169,
	18, 320, 162, 322, 324, 47, 46, 95, 18, 161,
	18, 327, 18, 329, 325, 331, 337, 205, 78, 18,
	271, 303, 335, 160, 315, 307, 333, 309, 87, 205,
	280, 157, 47, 46, 59, 150, 317, 28, 319, 118,
	321, 99, 66, 65, 75, 92, 46, 47, 46, 290,
	328, 137, 293, 294, 295, 69, 70, 72, 73, 202,
	71, 62, 79, 78, 60, 334, 305, 306, 47, 46,
	268, 47, 46, 47, 46, 286, 336, 68, 67, 59,
	326, 6, 28, 318, 58, 41, 76, 66, 65, 75,
	302, 308, 269, 47, 46, 46, 174, 47, 46, 304,
	69, 70, 72, 73, 234, 71, 62, 79, 289, 60,
	130, 127, 131, 132, 128, 129, 47, 46, 42, 2,
	3, 1, 68, 67, 332, 130, 127, 131, 132, 58,
	129, 76, 23, 218, 101, 164, 125, 126, 120, 121,
	122, 123, 124, 130, 127, 131, 132, 128, 129, 49,
	230, 125, 126, 120, 121, 122, 123, 124, 130, 127,
	131, 132, 128, 129, 107, 22, 48, 31, 22, 125,
	126, 120, 121, 122, 123, 124, 130, 127, 131, 132,
	128, 129, 29, 223, 125, 126, 120, 121, 122, 123,
	124, 130, 127, 131, 132, 128, 129, 45, 176, 43,
	11, 297, 125, 126, 120, 121, 122, 123, 124, 235,
	110, 263, 313, 285, 174, 9, 10, 125, 126, 120,
	121, 122, 123, 124, 0, 0, 0, 232, 130, 127,
	131, 132, 128, 129, 0, 0, 0, 47, 46, 130,
	127, 131, 132, 128, 129, 330, 0, 0, 130, 127,
	131, 132, 128, 129, 125, 126, 120, 121, 122, 123,
	124, 0, 0, 240, 198, 125, 126, 120, 121, 122,
	123, 124, 152, 0, 125, 126, 120, 121, 122, 123,
	124, 130, 127, 131, 132, 128, 129, 0, 47, 46,
	130, 127, 131, 132, 128, 129, 323, 106, 21, 104,
	19, 21, 0, 19, 151, 149, 0, 125, 126, 120,
	121, 122, 123, 124, 0, 0, 125, 126, 120, 121,
	122, 123, 124, 130, 127, 131, 132, 128, 129, 0,
	0, 130, 127, 131, 132, 128, 129, 0, 130, 127,
	131, 132, 128, 129, 103, 20, 0, 0, 20, 125,
	126, 120, 121, 122, 123, 124, 0, 125, 126, 120,
	121, 122, 123, 124, 125, 126, 120, 121, 122, 123,
	124, 38, 39, 0, 33, 0, 0, 24, 0, 0,
	0, 0, 25, 0, 0, 0, 0, 0, 13, 0,
	0, 26, 28, 12, 27, 0, 0, 0, 0, 0,
	30, 0, 15, 14, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 17, 16, 32, 0,
	7, 8, 34, 0, 38, 39, 35, 33, 36, 0,
	24, 0, 0, 0, 0, 25, 0, 0, 0, 0,
	0, 13, 0, 28, 26, 28, 12, 27, 66, 65,
	0, 0, 0, 30, 0, 15, 14, 0, 0, 0,
	0, 69, 70, 72, 73, 0, 71, 0, 0, 17,
	16, 32, 0, 7, 8, 34, 24, 0, 0, 35,
	0, 25, 0, 68, 67, 0, 0, 13, 0, 0,
	26, 28, 12, 27, 0, 0, 0, 0, 0, 0,
	0, 15, 14, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 17, 16, 0, 0, 7,
	8,
}

var yyPact = [...]int16{
	674, -1000, -1000, 674, -1000, 403, -1000, -1000, -45, -1000,
	-1000, -1000, -1000, -1000, 364, 364, 157, 186, -1000, -1000,
	-1000, -1000, -1000, -1000, 364, 319, 364, 773, -1000, 277,
	346, 263, 208, 342, 727, 727, -1000, -1000, -1000, 58,
	403, -1000, -1000, 773, -1000, -1000, -1000, -1000, -12, -1000,
	364, -54, -1000, 340, 364, -1000, 608, -1000, 364, 364,
	364, -1000, 186, -1000, -41, -1000, -1000, 364, 364, -1000,
	-1000, -1000, -1000, -1000, -1000, 163, 48, -47, 24, 56,
	-1000, -1000, 364, -1000, -1000, -1000, 601, 336, 593, 560,
	245, 283, 20, -1000, 332, 195, 324, 310, 303, 18,
	-1000, 727, -1000, -1000, -1000, 351, -1000, -1000, 89, 178,
	-1000, -1000, 300, 364, 364, 143, -1000, -1000, 16, 428,
	364, 364, 364, 364, 364, 364, 364, 364, 364, 364,
	364, 364, 364, 141, 212, 212, -1000, 180, -1000, -1000,
	-1000, 14, 364, 364, 364, 364, -1000, 364, 498, 773,
	232, 364, -1000, -1000, 189, -1000, 219, 8, 296, 294,
	0, -3, -4, 219, 127, -1000, -1000, -1000, -28, -5,
	413, 608, -54, 364, -1000, 364, -1000, 105, 105, -1000,
	-1000, -1000, 188, 188, -13, 395, 37, 113, 44, 212,
	-1000, -47, 364, 126, 518, 380, 123, 461, -1000, 399,
	11, 551, 773, 773, 351, 293, -1000, 120, 132, -1000,
	286, 219, -6, -25, 219, 219, 219, 118, 90, 727,
	727, -1000, 364, -1000, -54, -1000, 116, 114, -1000, 364,
	-1000, -1000, -1000, 250, 364, 207, -41, -1000, 165, -1000,
	-1000, 379, 259, -1000, -1000, 128, 219, 725, -1000, 95,
	219, 219, 94, 92, 91, 128, -1000, -1000, -1000, 88,
	-1000, -1000, 518, 198, 773, 509, -1000, -29, 773, -1000,
	-1000, -1000, 132, -1000, 128, 86, 43, 128, 128, 128,
	264, -1000, 364, -1000, 403, 773, 773, -1000, 377, 264,
	-1000, 128, 128, 264, -1000, 264, 773, 274, 283, 446,
	399, 311, -1000, 773, 264, -1000, 264, 773, 264, 773,
	594, 283, 400, -1000, -1000, -1000, 353, 773, 264, 773,
	543, 773, 422, -1000, 400, -1000, -1000, 338, 773, 374,
	-1000, 289, -1000, -1000, -1000, 193, -1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 428, 3, 16, 526, 654, 525, 5, 521, 520,
	17, 13, 84, 6, 10, 8, 27, 45, 23, 519,
	12, 22, 41, 511, 2, 510, 21, 0, 509, 11,
	507, 609, 14, 235, 492, 477, 476, 459, 15, 9,
	607, 445, 26, 444, 19, 443, 474, 442, 431, 430,
	391, 418, 409, 401, 393, 385, 380, 369, 361, 298,
}

var yyR1 = [...]int8{
	0, 48, 48, 48, 49, 49, 50, 50, 50, 50,
	50, 33, 33, 34, 34, 35, 35, 12, 12, 31,
	51, 5, 52, 5, 53, 5, 54, 5, 5, 5,
	5, 5, 2, 2, 1, 1, 9, 9, 28, 28,
	22, 22, 23, 23, 6, 7, 7, 8, 8, 21,
	55, 4, 56, 4, 57, 4, 19, 19, 19, 19,
	36, 36, 36, 36, 37, 37, 37, 37, 38, 38,
	39, 39, 39, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 18, 18, 26, 26,
	26, 26, 26, 17, 17, 59, 25, 40, 41, 41,
	45, 45, 42, 42, 43, 43, 44, 44, 44, 44,
	44, 46, 47, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 16, 16, 10, 10, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 15, 15,
	15, 14, 14, 14, 20, 20, 20, 27, 24, 24,
	29, 30, 32, 58,
}

var yyR2 = [...]int8{
	0, 0, 1, 2, 1, 2, 1, 1, 1, 1,
	1, 1, 4, 0, 1, 1, 2, 0, 1, 5,
	0, 10, 0, 11, 0, 11, 0, 12, 9, 10,
	10, 11, 0, 1, 1, 3, 0, 1, 1, 1,
	0, 1, 3, 4, 7, 0, 5, 0, 2, 8,
	0, 9, 0, 8, 0, 6, 1, 1, 3, 1,
	0, 3, 6, 4, 0, 3, 4, 1, 1, 2,
	2, 5, 3, 4, 2, 1, 1, 1, 1, 1,
	2, 2, 2, 4, 2, 1, 1, 3, 1, 4,
	4, 2, 4, 1, 1, 0, 6, 5, 0, 3,
	0, 2, 0, 1, 1, 2, 1, 1, 2, 1,
	1, 3, 1, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 2, 2,
	1, 2, 1, 1, 0, 1, 1, 3, 1, 1,
	2, 2, 1, 1, 1, 1, 1, 1, 1, 2,
	3, 0, 1, 3, 2, 5, 4, 1, 1, 3,
	1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -48, -1, -49, -3, -2, -50, 56, 57, -6,
	-4, -25, 29, 24, 39, 38, 53, 52, -27, -31,
	-5, -40, -46, -47, 13, 18, 27, 30, 28, -34,
	36, -35, 54, 10, 58, 62, 64, -33, 7, 8,
	-2, -50, -1, -28, -29, -30, 5, 4, -36, -37,
	75, -38, -39, 78, 79, -16, -11, -13, 75, 25,
	55, -20, 52, -21, -18, 34, 33, 69, 68, 46,
	47, 51, 48, 49, -27, 35, 77, -26, 9, 53,
	-16, -17, 75, 34, 9, -27, -11, 19, -11, -11,
	-2, 11, 9, -33, 36, 54, 10, 36, 10, 9,
	-42, -43, -44, -5, -31, -3, -40, -46, -42, 75,
	-9, -3, 78, 79, 41, -10, -16, -39, 9, -11,
	68, 69, 70, 71, 72, 66, 67, 41, 44, 45,
	40, 42, 43, -10, -11, -11, -27, -58, 78, -11,
	-11, 9, 75, 75, 79, 75, -17, 75, -11, 14,
	9, 21, 22, 31, -24, 9, 75, 9, 36, 10,
	9, 9, 9, 75, -41, -44, -29, 63, 34, 9,
	-11, -11, 76, -32, 6, 75, 80, -11, -11, -11,
	-11, -11, -11, -11, -11, -11, -11, -11, -11, -11,
	76, -26, 75, -10, -11, -11, -10, -11, 76, -2,
	20, -11, -57, -59, -12, -32, 50, -14, -15, 9,
	26, 75, 9, 9, 75, 75, 75, -14, -45, 59,
	60, 76, 75, 80, -38, -16, -10, -10, 76, -32,
	80, 76, 76, -7, 15, -19, -18, -20, 75, -21,
	22, -2, -2, -29, 9, 76, -32, 41, 9, -14,
	75, 75, -14, -14, -14, 76, 61, -42, -42, -10,
	76, 76, -11, -8, 16, -11, 22, -20, -56, 23,
	32, -12, -15, -13, 76, -14, -14, 76, 76, 76,
	-12, 76, -32, 17, -2, 14, -55, 76, -2, -51,
	-12, 76, 76, -12, -12, -12, -22, -23, 11, -11,
	-2, -2, 23, -22, -52, -12, -12, -22, -53, -22,
	-2, 11, -24, 76, -7, 23, -2, -22, -54, -22,
	-2, -22, -2, 12, -24, -29, 37, -2, -22, -2,
	12, -2, 12, -29, 37, -2, 12, 37, 37,
}

var yyDef = [...]int16{
	-2, -2, -2, -2, 34, 0, 4, 60, 64, 75,
	76, 77, 78, 79, 134, 134, 0, 0, 85, 6,
	7, 8, 9, 10, 0, 0, 0, 32, 157, 0,
	0, 0, 0, 0, -2, -2, 112, -2, 11, 0,
	3, 5, 33, 36, 38, 39, 160, 161, 0, 74,
	134, 67, 68, 0, 0, 80, 135, 113, 134, 0,
	0, 130, 0, 132, 133, 138, 139, 0, 0, 142,
	143, 144, 145, 146, 147, 0, 0, 86, 88, 0,
	81, 82, 0, 93, 94, 84, 0, 0, 0, 0,
	0, 0, 0, 16, 0, 0, 0, 0, 0, 0,
	98, -2, 104, 106, 107, 0, 109, 110, 0, 0,
	35, 37, 0, 0, 0, 0, 136, 69, 70, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 128, 129, 131, 0, 163, 140,
	141, 154, 134, 0, 0, 134, 91, 0, 0, 32,
	0, 0, 54, 95, 17, 158, 151, 0, 0, 0,
	0, 0, 0, 151, 100, 105, 108, 111, 0, 61,
	0, 73, 65, 134, 162, 134, 72, 115, 116, 117,
	118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
	114, 87, 134, 0, 0, 0, 0, 0, 83, 45,
	0, 0, 32, 32, 0, 0, 18, 0, 152, 148,
	0, 151, 0, 0, 151, 151, 151, 0, 0, -2,
	-2, 12, 134, 63, 66, 137, 0, 0, 156, 0,
	90, 89, 92, 47, 0, 0, 56, 57, 0, 59,
	52, 0, 0, 19, 159, 17, 0, 0, 149, 0,
	151, 151, 0, 0, 0, 17, 97, 99, 101, 0,
	71, 155, 0, 0, 32, 0, 50, 0, 32, 55,
	96, 20, 153, 150, 17, 0, 0, 17, 17, 17,
	40, 62, 0, 44, 48, 32, 32, 58, 0, 40,
	22, 17, 17, 40, 24, 40, 32, 41, 0, 0,
	45, 0, 53, 32, 40, 26, 40, 32, 40, 32,
	0, 0, 0, 49, 46, 51, 0, 32, 40, 32,
	0, 32, 0, 28, 0, 42, 21, 0, 32, 0,
	29, 0, 30, 43, 23, 0, 31, 25, 27,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 72, 3, 3,
	75, 76, 70, 68, 6, 69, 78, 71, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 5,
	67, 3, 66, 77, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 79, 3, 80,
}

var yyTok2 = [...]int8{
	2, 3, 7, 8, 9, 10, 11, 12, 13, 14,
	15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
	35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
	45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
	55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
	65, 73, 74,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:103
		{
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:104
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].body, yylex)
			}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:109
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[2].opt_body, yylex)
			}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:119
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].global_variables, yylex)
			}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:124
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].funcProc, yylex)
			}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:129
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].preproc_if, yylex)
			}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:134
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].region_stmt, yylex)
			}
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:139
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].use_stmt, yylex)
			}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:148
		{
			yyVAL.directive = &DirectiveStatement{Name: yyDollar[1].token.literal}
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:149
		{
			yyVAL.directive = &DirectiveStatement{Name: yyDollar[1].token.literal, Src: yyDollar[3].token.literal}
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:152
		{
			yyVAL.directive = nil
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:153
		{
			yyVAL.directive = yyDollar[1].directive
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:156
		{
			yyVAL.directives = []*DirectiveStatement{yyDollar[1].directive}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:157
		{
			yyVAL.directives = append(yyVAL.directives, yyDollar[2].directive)
		}
	case 17:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:160
		{
			yyVAL.opt_export = nil
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:161
		{
			yyVAL.opt_export = &yyDollar[1].token
		}
	case 19:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:164
		{
			yyVAL.global_variables = make([]GlobalVariables, len(yyDollar[3].identifiers), len(yyDollar[3].identifiers))
			for i, v := range yyDollar[3].identifiers {
				if yyDollar[1].directive != nil {
					yyVAL.global_variables[i].Directive = yyDollar[1].directive
				}

				yyVAL.global_variables[i].Export = yyDollar[4].opt_export != nil
				yyVAL.global_variables[i].Var = VarStatement{Name: v.literal}
			}
		}
	case 20:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ast/grammar.y:178
		{
			isFunction(true, yylex)
		}
	case 21:
		yyDollar = yyS[yypt-10 : yypt+1]
//line ast/grammar.y:179
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeFunction, nil, nil, yyDollar[2].token.literal, yyDollar[4].declarations_method_params, yyDollar[6].opt_export, yyDollar[8].opt_explicit_variables, yyDollar[9].opt_body)
			isFunction(false, yylex)
		}
	case 22:
		yyDollar = yyS[yypt-7 : yypt+1]
//line ast/grammar.y:183
		{
			isFunction(true, yylex)
		}
	case 23:
		yyDollar = yyS[yypt-11 : yypt+1]
//line ast/grammar.y:184
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeFunction, yyDollar[1].directives, nil, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[9].opt_explicit_variables, yyDollar[10].opt_body)
			isFunction(false, yylex)
		}
	case 24:
		yyDollar = yyS[yypt-7 : yypt+1]
//line ast/grammar.y:188
		{
			isFunction(true, yylex)
		}
	case 25:
		yyDollar = yyS[yypt-11 : yypt+1]
//line ast/grammar.y:189
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeFunction, nil, &yyDollar[1].token, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[9].opt_explicit_variables, yyDollar[10].opt_body)
			isFunction(false, yylex)
		}
	case 26:
		yyDollar = yyS[yypt-8 : yypt+1]
//line ast/grammar.y:193
		{
			isFunction(true, yylex)
		}
	case 27:
		yyDollar = yyS[yypt-12 : yypt+1]
//line ast/grammar.y:194
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeFunction, yyDollar[1].directives, &yyDollar[2].token, yyDollar[4].token.literal, yyDollar[6].declarations_method_params, yyDollar[8].opt_export, yyDollar[10].opt_explicit_variables, yyDollar[11].opt_body)
			isFunction(false, yylex)
		}
	case 28:
		yyDollar = yyS[yypt-9 : yypt+1]
//line ast/grammar.y:199
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeProcedure, nil, nil, yyDollar[2].token.literal, yyDollar[4].declarations_method_params, yyDollar[6].opt_export, yyDollar[7].opt_explicit_variables, yyDollar[8].opt_body)
		}
	case 29:
		yyDollar = yyS[yypt-10 : yypt+1]
//line ast/grammar.y:203
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeProcedure, yyDollar[1].directives, nil, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[8].opt_explicit_variables, yyDollar[9].opt_body)
		}
	case 30:
		yyDollar = yyS[yypt-10 : yypt+1]
//line ast/grammar.y:207
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeProcedure, nil, &yyDollar[1].token, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[8].opt_explicit_variables, yyDollar[9].opt_body)
		}
	case 31:
		yyDollar = yyS[yypt-11 : yypt+1]
//line ast/grammar.y:211
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeProcedure, yyDollar[1].directives, &yyDollar[2].token, yyDollar[4].token.literal, yyDollar[6].declarations_method_params, yyDollar[8].opt_export, yyDollar[9].opt_explicit_variables, yyDollar[10].opt_body)
		}
	case 32:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:216
		{
			yyVAL.opt_body = nil
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:217
		{
			yyVAL.opt_body = yyDollar[1].body
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:221
		{
			yyVAL.body = Statements{yyDollar[1].stmt}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:222
		{
			if yyDollar[2].token.literal == ":" && len(yyDollar[1].opt_body) > 0 {
				if _, ok := yyDollar[1].opt_body[len(yyDollar[1].opt_body)-1].(*GoToLabelStatement); !ok {
					yylex.Error("semicolon (;) is expected")
				}
			}
			if yyDollar[3].stmt != nil {
				yyVAL.body = append(yyVAL.body, yyDollar[3].stmt)
			}
		}
	case 36:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:235
		{
			yyVAL.stmt = nil
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:236
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:239
		{
			yyVAL.token = yyDollar[1].token
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:239
		{
			yyVAL.token = yyDollar[1].token
		}
	case 40:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:243
		{
			yyVAL.opt_explicit_variables = map[string]VarStatement{}
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:244
		{
			yyVAL.opt_explicit_variables = yyDollar[1].explicit_variables
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:247
		{
			if vars, err := appendVarStatements(map[string]VarStatement{}, yyDollar[2].identifiers); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.explicit_variables = vars
			}
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:254
		{
			if vars, err := appendVarStatements(yyDollar[1].explicit_variables, yyDollar[3].identifiers); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.explicit_variables = vars
			}
		}
	case 44:
		yyDollar = yyS[yypt-7 : yypt+1]
//line ast/grammar.y:265
		{
			yyVAL.stmt_if = &IfStatement{
				Expression:  yyDollar[2].stmt,
				TrueBlock:   yyDollar[4].opt_body,
				IfElseBlock: yyDollar[5].opt_elseif_list,
				ElseBlock:   yyDollar[6].opt_else,
			}
		}
	case 45:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:275
		{
			yyVAL.opt_elseif_list = Statements{}
		}
	case 46:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:276
		{
			yyVAL.opt_elseif_list = append(yyDollar[5].opt_elseif_list, &IfStatement{
				Expression: yyDollar[2].stmt,
				TrueBlock:  yyDollar[4].opt_body,
			})
		}
	case 47:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:284
		{
			yyVAL.opt_else = nil
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:285
		{
			yyVAL.opt_else = yyDollar[2].opt_body
		}
	case 49:
		yyDollar = yyS[yypt-8 : yypt+1]
//line ast/grammar.y:288
		{
			yyVAL.stmt = TernaryStatement{
				Expression: yyDollar[3].stmt,
				TrueBlock:  yyDollar[5].stmt,
				ElseBlock:  yyDollar[7].stmt,
			}
		}
	case 50:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ast/grammar.y:297
		{
			setLoopFlag(true, yylex)
		}
	case 51:
		yyDollar = yyS[yypt-9 : yypt+1]
//line ast/grammar.y:297
		{
			yyVAL.stmt_loop = &LoopStatement{
				For:  yyDollar[3].token.literal,
				In:   yyDollar[5].stmt,
				Body: yyDollar[8].opt_body,
			}
			setLoopFlag(false, yylex)
		}
	case 52:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:305
		{
			setLoopFlag(true, yylex)
		}
	case 53:
		yyDollar = yyS[yypt-8 : yypt+1]
//line ast/grammar.y:305
		{
			yyVAL.stmt_loop = &LoopStatement{
				For:  yyDollar[2].stmt,
				To:   yyDollar[4].stmt,
				Body: yyDollar[7].opt_body,
			}
			setLoopFlag(false, yylex)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:313
		{
			setLoopFlag(true, yylex)
		}
	case 55:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ast/grammar.y:313
		{
			yyVAL.stmt_loop = &LoopStatement{
				WhileExpr: yyDollar[2].stmt,
				Body:      yyDollar[5].opt_body,
			}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:322
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:323
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:324
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:325
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 60:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:334
		{
			yyVAL.stmt = nil
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:335
		{
			prop := VarStatement{Name: yyDollar[3].token.literal}
			if yyDollar[1].stmt != nil {
				yyVAL.stmt = CallChainStatement{Unit: prop, Call: yyDollar[1].stmt}
			} else {
				yyVAL.stmt = prop
			}
		}
	case 62:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ast/grammar.y:343
		{
			method := MethodStatement{Name: yyDollar[3].token.literal, Param: yyDollar[5].exprs}
			if yyDollar[1].stmt != nil {
				yyVAL.stmt = CallChainStatement{Unit: method, Call: yyDollar[1].stmt}
			} else {
				yyVAL.stmt = method
			}
		}
	case 63:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:351
		{
			if yyDollar[1].stmt != nil {
				yyVAL.stmt = ItemStatement{Object: yyDollar[1].stmt, Item: yyDollar[3].stmt}
			} else {
				yyVAL.stmt = ItemStatement{Object: nil, Item: yyDollar[3].stmt}
			}
		}
	case 64:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:364
		{
			yyVAL.stmt = nil
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:365
		{
			// Foo() — вызов метода
			yyVAL.stmt = MethodStatement{Name: "", Param: yyDollar[2].exprs}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:369
		{
			// Foo().Bar... — вызов с продолжением
			method := MethodStatement{Name: "", Param: yyDollar[2].exprs}
			yyVAL.stmt = CallChainStatement{Unit: yyDollar[4].stmt, Call: method}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:374
		{
			// .свойство, .Метод(), [индекс] или их цепочка
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:383
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:384
		{
			yyVAL.stmt = CallChainStatement{Unit: yyDollar[2].stmt, Call: yyDollar[1].stmt}
		}
	case 70:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:389
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[2].token.literal}
		}
	case 71:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:392
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[2].token.literal, Param: yyDollar[4].exprs}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:395
		{
			yyVAL.stmt = ItemStatement{Object: nil, Item: yyDollar[2].stmt}
		}
	case 73:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:405
		{
			// Присваивание: а = 1, а.б = 1, а.Метод().в = 1
			lhs := VarStatement{Name: yyDollar[1].token.literal}
			if yyDollar[2].stmt != nil {
				yyVAL.stmt = AssignmentStatement{Var: CallChainStatement{Unit: yyDollar[2].stmt, Call: lhs}, Expr: ExprStatements{Statements: Statements{yyDollar[4].stmt}}}
			} else {
				yyVAL.stmt = AssignmentStatement{Var: lhs, Expr: ExprStatements{Statements: Statements{yyDollar[4].stmt}}}
			}
		}
	case 74:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:414
		{
			// Вызов как statement: Foo(), а.Метод(), а.б
			if yyDollar[2].stmt == nil {
				// Голый идентификатор: а;
				yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
			} else if method, ok := yyDollar[2].stmt.(MethodStatement); ok && method.Name == "" {
				// Простой вызов Foo() — НЕ оборачиваем в CallChainStatement
				method.Name = yyDollar[1].token.literal
				yyVAL.stmt = method
			} else {
				// Цепочка: а.Метод(), а.б, а[0]
				base := VarStatement{Name: yyDollar[1].token.literal}
				yyVAL.stmt = CallChainStatement{Unit: yyDollar[2].stmt, Call: base}
			}
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:429
		{
			yyVAL.stmt = yyDollar[1].stmt_if
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:430
		{
			yyVAL.stmt = yyDollar[1].stmt_loop
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:431
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:432
		{
			yyVAL.stmt = ContinueStatement{}
			checkLoopOperator(yyDollar[1].token, yylex)
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:433
		{
			yyVAL.stmt = BreakStatement{}
			checkLoopOperator(yyDollar[1].token, yylex)
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:434
		{
			yyVAL.stmt = ThrowStatement{Param: yyDollar[2].stmt}
			checkThrowParam(yyDollar[1].token, yyDollar[2].stmt, yylex)
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:435
		{
			yyVAL.stmt = &ReturnStatement{Param: yyDollar[2].stmt}
			checkReturnParam(yyDollar[2].stmt, yylex)
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:436
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[2].stmt}}}
		}
	case 83:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:437
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[3].stmt}}}
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:438
		{
			yyVAL.stmt = GoToStatement{Label: yyDollar[2].goToLabel}
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:439
		{
			yyVAL.stmt = yyDollar[1].goToLabel
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:444
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:445
		{
			yyVAL.stmt = CallChainStatement{Unit: yyDollar[3].stmt, Call: yyDollar[1].stmt}
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:451
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
		}
	case 89:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:452
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: yyDollar[3].exprs}
		}
	case 90:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:453
		{
			yyVAL.stmt = ItemStatement{Object: yyDollar[1].stmt, Item: yyDollar[3].stmt}
		}
	case 91:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:454
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[2].stmt}}}
		}
	case 92:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:455
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[3].stmt}}}
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:458
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:459
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:462
		{
			setTryFlag(true, yylex)
		}
	case 96:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ast/grammar.y:462
		{
			yyVAL.stmt = TryStatement{Body: yyDollar[2].opt_body, Catch: yyDollar[5].opt_body}
			setTryFlag(false, yylex)
		}
	case 97:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:467
		{
			yyVAL.preproc_if = &PreprocessorIfStatement{
				Condition: yyDollar[1].token.literal,
				ThenBlock: yyDollar[2].preproc_body,
				ElseIfs:   yyDollar[3].preproc_elseifs,
				ElseBlock: yyDollar[4].preproc_body,
			}
		}
	case 98:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:476
		{
			yyVAL.preproc_elseifs = nil
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:477
		{
			yyVAL.preproc_elseifs = append(yyDollar[1].preproc_elseifs, PreprocessorElseIf{Condition: yyDollar[2].token.literal, Block: yyDollar[3].preproc_body})
		}
	case 100:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:482
		{
			yyVAL.preproc_body = nil
		}
	case 101:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:483
		{
			yyVAL.preproc_body = yyDollar[2].preproc_body
		}
	case 102:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:486
		{
			yyVAL.preproc_body = nil
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:487
		{
			yyVAL.preproc_body = yyDollar[1].preproc_body
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:490
		{
			yyVAL.preproc_body = yyDollar[1].preproc_body
		}
	case 105:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:491
		{
			yyVAL.preproc_body = append(yyDollar[1].preproc_body, yyDollar[2].preproc_body...)
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:494
		{
			yyVAL.preproc_body = Statements{yyDollar[1].funcProc}
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:495
		{
			stmts := make(Statements, len(yyDollar[1].global_variables))
			for i, gv := range yyDollar[1].global_variables {
				stmts[i] = gv
			}
			yyVAL.preproc_body = stmts
		}
	case 108:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:502
		{
			yyVAL.preproc_body = Statements{yyDollar[1].stmt}
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:503
		{
			yyVAL.preproc_body = Statements{yyDollar[1].preproc_if}
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:504
		{
			yyVAL.preproc_body = Statements{yyDollar[1].region_stmt}
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:507
		{
			yyVAL.region_stmt = &RegionStatement{
				Name: yyDollar[1].token.literal,
				Body: yyDollar[2].preproc_body,
			}
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:514
		{
			yyVAL.use_stmt = &UseStatement{
				Path: yyDollar[1].token.literal,
			}
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:521
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:522
		{
			yyVAL.stmt = yyDollar[2].exprs
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:523
		{
			yyVAL.stmt = &ExpStatement{Operation: OpPlus, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:524
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMinus, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:525
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMul, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:526
		{
			yyVAL.stmt = &ExpStatement{Operation: OpDiv, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:527
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMod, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:528
		{
			yyVAL.stmt = &ExpStatement{Operation: OpGt, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:529
		{
			yyVAL.stmt = &ExpStatement{Operation: OpLt, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 122:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:530
		{
			yyVAL.stmt = &ExpStatement{Operation: OpEq, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 123:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:531
		{
			yyVAL.stmt = &ExpStatement{Operation: OpOr, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:532
		{
			yyVAL.stmt = &ExpStatement{Operation: OpAnd, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:533
		{
			yyVAL.stmt = &ExpStatement{Operation: OpNe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:534
		{
			yyVAL.stmt = &ExpStatement{Operation: OpLe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:535
		{
			yyVAL.stmt = &ExpStatement{Operation: OpGe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:536
		{
			yyVAL.stmt = not(yyDollar[2].stmt)
		}
	case 129:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:537
		{
			yyVAL.stmt = AwaitStatement{Expr: yyDollar[2].stmt}
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:538
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 131:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:539
		{
			yyVAL.stmt = GoToStatement{Label: yyDollar[2].goToLabel}
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:540
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:541
		{
			if tok, ok := yyDollar[1].stmt.(Token); ok {
				yyVAL.stmt = tok.literal
			} else {
				yyVAL.stmt = yyDollar[1].stmt
			}
		}
	case 134:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:550
		{
			yyVAL.stmt = nil
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:550
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:552
		{
			yyVAL.exprs = ExprStatements{Statements: Statements{yyDollar[1].stmt}}
		}
	case 137:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:553
		{
			yyVAL.exprs.Statements = append(yyVAL.exprs.Statements, yyDollar[3].stmt)
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:556
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:557
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 140:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:558
		{
			yyVAL.stmt = unaryMinus(yyDollar[2].stmt)
		}
	case 141:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:559
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:560
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:561
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:562
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:563
		{
			yyVAL.stmt = UndefinedStatement{}
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:564
		{
			yyVAL.stmt = NullStatement{}
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:565
		{
			yyVAL.stmt = yyDollar[1].goToLabel
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:569
		{
			yyVAL.declarations_method_param = *(&ParamStatement{}).Fill(nil, yyDollar[1].token)
		}
	case 149:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:570
		{
			yyVAL.declarations_method_param = *(&ParamStatement{}).Fill(&yyDollar[1].token, yyDollar[2].token)
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:571
		{
			yyVAL.declarations_method_param = *(yyVAL.declarations_method_param.DefaultValue(yyDollar[3].stmt))
		}
	case 151:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:574
		{
			yyVAL.declarations_method_params = []ParamStatement{}
		}
	case 152:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:575
		{
			yyVAL.declarations_method_params = []ParamStatement{yyDollar[1].declarations_method_param}
		}
	case 153:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:576
		{
			yyVAL.declarations_method_params = append(yyDollar[1].declarations_method_params, yyDollar[3].declarations_method_param)
		}
	case 154:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:584
		{
			yyVAL.stmt = NewObjectStatement{Constructor: yyDollar[2].token.literal}
		}
	case 155:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:585
		{
			yyVAL.stmt = NewObjectStatement{Constructor: yyDollar[2].token.literal, Param: yyDollar[4].exprs}
		}
	case 156:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:586
		{
			yyVAL.stmt = NewObjectStatement{Param: yyDollar[3].exprs}
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:591
		{
			yyVAL.goToLabel = &GoToLabelStatement{Name: yyDollar[1].token.literal}
		}
	case 158:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:593
		{
			yyVAL.identifiers = []Token{yyDollar[1].token}
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:594
		{
			yyVAL.identifiers = append(yyVAL.identifiers, yyDollar[3].token)
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:597
		{
			yyVAL.token = yyDollar[1].token
		}
	case 161:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:598
		{
			yyVAL.token = yyDollar[1].token
		}
	case 162:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:599
		{
			yyVAL.token = yyDollar[1].token
		}
	}
	goto yystack /* stack new state and value */
}
