// Code generated by goyacc -v /tmp/y.output -o ast/y.go ast/grammar.y. DO NOT EDIT.

//line ast/grammar.y:2
package ast

import __yyfmt__ "fmt"

//line ast/grammar.y:2

//line ast/grammar.y:54
type yySymType struct {
	yys                        int
	token                      Token
	stmt_if                    *IfStatement
	opt_elseif_list            Statements
	opt_else                   Statements
	stmt                       Statement
	stmt_loop                  *LoopStatement
	funcProc                   *FunctionOrProcedure
	body                       Statements
	opt_body                   Statements
	declarations_method_params []ParamStatement
	declarations_method_param  ParamStatement
	exprs                      ExprStatements
	opt_export                 *Token
	explicit_variables         map[string]VarStatement
	global_variables           []GlobalVariables
	opt_explicit_variables     map[string]VarStatement
	identifiers                []Token
	goToLabel                  *GoToLabelStatement
	opt_goToLabel              *GoToLabelStatement
	directive                  *DirectiveStatement
	directives                 []*DirectiveStatement
	preproc_if                 *PreprocessorIfStatement
	preproc_elseifs            []PreprocessorElseIf
	preproc_body               Statements
	region_stmt                *RegionStatement
	use_stmt                   *UseStatement
}

const Directive = 57346
const ExtDirective = 57347
const token_identifier = 57348
const Procedure = 57349
const Var = 57350
const EndProcedure = 57351
const If = 57352
const Then = 57353
const ElseIf = 57354
const Else = 57355
const EndIf = 57356
const For = 57357
const Each = 57358
const In = 57359
const To = 57360
const Loop = 57361
const EndLoop = 57362
const Break = 57363
const Not = 57364
const ValueParam = 57365
const While = 57366
const GoToLabel = 57367
const Continue = 57368
const Try = 57369
const Catch = 57370
const EndTry = 57371
const Number = 57372
const String = 57373
const New = 57374
const Function = 57375
const EndFunction = 57376
const Return = 57377
const Throw = 57378
const NeEQ = 57379
const EQUAL = 57380
const LE = 57381
const GE = 57382
const OR = 57383
const And = 57384
const True = 57385
const False = 57386
const Undefined = 57387
const Export = 57388
const Date = 57389
const GoTo = 57390
const Execute = 57391
const LVALUE_IDENT = 57392
const CALL_IDENT = 57393
const PreprocIf = 57394
const PreprocElseIf = 57395
const PreprocElse = 57396
const PreprocEndIf = 57397
const PreprocRegion = 57398
const PreprocEndRegion = 57399
const PreprocUse = 57400
const LOW_PREC = 57401
const UNARMinus = 57402
const UNARYPlus = 57403

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"':'",
	"';'",
	"','",
	"Directive",
	"ExtDirective",
	"token_identifier",
	"Procedure",
	"Var",
	"EndProcedure",
	"If",
	"Then",
	"ElseIf",
	"Else",
	"EndIf",
	"For",
	"Each",
	"In",
	"To",
	"Loop",
	"EndLoop",
	"Break",
	"Not",
	"ValueParam",
	"While",
	"GoToLabel",
	"Continue",
	"Try",
	"Catch",
	"EndTry",
	"Number",
	"String",
	"New",
	"Function",
	"EndFunction",
	"Return",
	"Throw",
	"NeEQ",
	"EQUAL",
	"LE",
	"GE",
	"OR",
	"And",
	"True",
	"False",
	"Undefined",
	"Export",
	"Date",
	"GoTo",
	"Execute",
	"LVALUE_IDENT",
	"CALL_IDENT",
	"PreprocIf",
	"PreprocElseIf",
	"PreprocElse",
	"PreprocEndIf",
	"PreprocRegion",
	"PreprocEndRegion",
	"PreprocUse",
	"LOW_PREC",
	"'>'",
	"'<'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARMinus",
	"UNARYPlus",
	"'('",
	"')'",
	"'?'",
	"'.'",
	"'['",
	"']'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line ast/grammar.y:577

//line yacctab:1
var yyExca = [...]int16{
	-1, 0,
	1, 1,
	10, 17,
	11, 13,
	36, 17,
	-2, 25,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 2,
	-2, 26,
	-1, 3,
	10, 17,
	11, 13,
	36, 17,
	-2, 25,
	-1, 31,
	10, 17,
	11, 13,
	36, 17,
	-2, 95,
	-1, 32,
	11, 13,
	60, 95,
	-2, 17,
	-1, 34,
	11, 14,
	-2, 15,
	-1, 91,
	10, 17,
	11, 13,
	36, 17,
	-2, 96,
	-1, 194,
	10, 17,
	11, 13,
	36, 17,
	-2, 95,
	-1, 195,
	11, 13,
	58, 95,
	-2, 17,
}

const yyPrivate = 57344

const yyLast = 717

var yyAct = [...]int16{
	70, 18, 5, 157, 18, 42, 38, 208, 144, 54,
	262, 50, 55, 188, 4, 221, 58, 90, 81, 60,
	106, 61, 220, 107, 73, 92, 49, 134, 18, 77,
	86, 105, 18, 18, 82, 84, 85, 74, 53, 76,
	48, 128, 18, 51, 52, 251, 95, 95, 51, 52,
	98, 158, 158, 158, 196, 197, 102, 192, 191, 176,
	126, 108, 110, 71, 159, 103, 104, 125, 135, 133,
	121, 118, 122, 123, 129, 130, 100, 124, 158, 158,
	75, 151, 158, 225, 121, 118, 122, 123, 138, 120,
	190, 80, 18, 116, 117, 111, 112, 113, 114, 115,
	213, 150, 72, 242, 71, 136, 95, 116, 117, 111,
	112, 113, 114, 115, 154, 155, 79, 149, 245, 244,
	240, 161, 162, 163, 164, 165, 166, 167, 168, 169,
	170, 171, 172, 173, 121, 118, 122, 123, 119, 120,
	18, 158, 183, 178, 179, 230, 229, 181, 189, 206,
	118, 185, 175, 177, 137, 34, 180, 116, 117, 111,
	112, 113, 114, 115, 116, 117, 111, 112, 113, 114,
	115, 205, 116, 117, 111, 112, 113, 114, 115, 89,
	201, 200, 204, 199, 194, 195, 131, 18, 18, 216,
	217, 99, 158, 158, 218, 18, 18, 202, 80, 45,
	44, 212, 152, 28, 214, 88, 211, 235, 203, 95,
	95, 108, 226, 227, 231, 224, 222, 184, 228, 234,
	118, 122, 123, 79, 241, 113, 114, 115, 241, 247,
	236, 233, 276, 223, 18, 246, 248, 270, 18, 264,
	252, 87, 116, 117, 111, 112, 113, 114, 115, 132,
	18, 18, 258, 259, 253, 255, 257, 254, 256, 174,
	156, 78, 145, 18, 44, 269, 266, 45, 44, 18,
	243, 272, 268, 271, 118, 189, 123, 275, 189, 274,
	277, 121, 118, 122, 123, 119, 120, 74, 121, 118,
	122, 123, 119, 120, 219, 239, 116, 117, 111, 112,
	113, 114, 115, 158, 116, 117, 111, 112, 113, 114,
	115, 116, 117, 111, 112, 113, 114, 115, 198, 74,
	111, 112, 113, 114, 115, 160, 153, 45, 44, 83,
	75, 28, 187, 45, 44, 57, 63, 62, 28, 147,
	45, 44, 146, 63, 62, 71, 190, 140, 74, 66,
	67, 69, 267, 68, 143, 109, 66, 67, 69, 260,
	68, 59, 75, 127, 57, 36, 37, 28, 65, 64,
	45, 44, 63, 62, 71, 65, 64, 44, 158, 45,
	44, 209, 56, 186, 72, 66, 67, 69, 237, 68,
	59, 75, 121, 118, 122, 123, 119, 120, 238, 45,
	44, 250, 45, 44, 65, 64, 6, 273, 97, 22,
	39, 56, 22, 72, 261, 116, 117, 111, 112, 113,
	114, 115, 40, 2, 3, 265, 121, 118, 122, 123,
	119, 120, 96, 21, 1, 23, 21, 121, 118, 122,
	123, 119, 120, 193, 158, 249, 91, 148, 47, 116,
	117, 111, 112, 113, 114, 115, 46, 30, 35, 207,
	116, 117, 111, 112, 113, 114, 115, 215, 29, 43,
	182, 121, 118, 122, 123, 119, 120, 41, 121, 118,
	122, 123, 119, 120, 11, 121, 118, 122, 123, 119,
	120, 263, 210, 101, 116, 117, 111, 112, 113, 114,
	115, 116, 117, 111, 112, 113, 114, 115, 116, 117,
	111, 112, 113, 114, 115, 142, 94, 19, 232, 9,
	19, 141, 139, 93, 20, 10, 0, 20, 0, 0,
	0, 0, 0, 121, 118, 122, 123, 119, 120, 0,
	121, 118, 122, 123, 119, 120, 0, 0, 121, 118,
	122, 123, 119, 120, 0, 0, 116, 117, 111, 112,
	113, 114, 115, 116, 117, 111, 112, 113, 114, 115,
	0, 116, 117, 111, 112, 113, 114, 115, 121, 118,
	122, 123, 119, 120, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 116, 117, 111, 112, 113, 114, 115, 36, 37,
	0, 0, 0, 0, 24, 0, 0, 0, 0, 25,
	0, 0, 0, 0, 0, 13, 36, 37, 26, 28,
	12, 27, 24, 0, 0, 0, 0, 25, 0, 15,
	14, 0, 0, 13, 0, 0, 26, 28, 12, 27,
	0, 0, 17, 16, 7, 8, 31, 15, 14, 0,
	32, 0, 33, 0, 0, 0, 0, 0, 0, 0,
	17, 16, 7, 8, 31, 24, 0, 0, 32, 0,
	25, 0, 0, 0, 0, 0, 13, 0, 0, 26,
	28, 12, 27, 0, 0, 0, 0, 0, 0, 0,
	15, 14, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 17, 16, 7, 8,
}

var yyPact = [...]int16{
	601, -1000, -1000, 601, -1000, 398, -1000, -1000, -32, -1000,
	-1000, -1000, -1000, -1000, 339, 339, 189, 175, -1000, -1000,
	-1000, -1000, -1000, -1000, 339, 310, 339, 662, -1000, 230,
	169, 619, 619, -1000, -1000, 358, -1000, 4, 398, -1000,
	-1000, 662, -1000, -1000, -1000, -1000, -10, -1000, 339, -27,
	-1000, 346, 339, -1000, 538, -1000, 339, 339, -1000, 175,
	-1000, -34, -1000, -1000, 339, 339, -1000, -1000, -1000, -1000,
	-1000, 177, -3, -49, -4, 82, -1000, -1000, 339, -1000,
	-1000, -1000, 508, 338, 500, 493, 323, 253, 333, 330,
	-1000, 619, -1000, -1000, -1000, 259, -1000, -1000, 21, -1000,
	168, -1000, -1000, 317, 339, 339, 187, -1000, -1000, -8,
	248, 339, 339, 339, 339, 339, 339, 339, 339, 339,
	339, 339, 339, 339, 186, 109, -1000, 278, -1000, -1000,
	-1000, -13, 339, 339, 339, 339, -1000, 339, 397, 662,
	197, 339, -1000, -1000, 297, -1000, -14, -15, 128, -1000,
	-1000, -1000, -19, -17, 241, 538, -27, 339, -1000, 339,
	-1000, 158, 158, -1000, -1000, -1000, 255, 255, 101, 44,
	30, 179, 233, 109, -1000, -49, 339, 135, 438, 94,
	76, 386, -1000, 366, 28, 445, 662, 662, 259, 285,
	-1000, 207, 207, 25, 619, 619, -1000, 339, -1000, -27,
	-1000, 73, 72, -1000, 339, -1000, -1000, -1000, 215, 339,
	185, -34, -1000, 69, -1000, -1000, 375, 263, -1000, -1000,
	47, 62, -1000, 261, 46, -1000, -1000, -1000, 45, -1000,
	-1000, 438, 212, 662, 431, -1000, -28, 662, -1000, -1000,
	41, 207, 303, -1000, 41, -1000, 339, -1000, 398, 662,
	662, -1000, 336, -1000, 62, -1000, 228, 352, 366, 329,
	-1000, 228, 662, 226, 253, -1000, -1000, -1000, 662, 395,
	253, 372, 195, -1000, 372, -1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 422, 2, 14, 525, 523, 519, 7, 518, 493,
	20, 9, 13, 12, 22, 15, 23, 29, 21, 492,
	16, 19, 10, 491, 8, 484, 24, 0, 477, 5,
	469, 516, 3, 155, 468, 458, 457, 456, 448, 26,
	11, 432, 447, 17, 446, 25, 443, 408, 435, 434,
	424, 406, 414, 401, 388, 383, 363, 332,
}

var yyR1 = [...]int8{
	0, 49, 49, 49, 50, 50, 51, 51, 51, 51,
	51, 33, 33, 34, 34, 35, 35, 36, 36, 12,
	12, 31, 52, 5, 5, 2, 2, 1, 1, 9,
	9, 28, 28, 22, 22, 23, 23, 6, 7, 7,
	8, 8, 21, 53, 4, 54, 4, 55, 4, 19,
	19, 19, 19, 37, 37, 37, 37, 38, 38, 38,
	38, 39, 39, 40, 40, 40, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 18,
	18, 26, 26, 26, 26, 26, 17, 17, 57, 25,
	41, 42, 42, 46, 46, 43, 43, 44, 44, 45,
	45, 45, 45, 45, 47, 48, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 16, 16, 10, 10,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 15,
	15, 15, 14, 14, 14, 20, 20, 20, 27, 24,
	24, 29, 30, 32, 56,
}

var yyR2 = [...]int8{
	0, 0, 1, 2, 1, 2, 1, 1, 1, 1,
	1, 1, 4, 0, 1, 1, 2, 0, 1, 0,
	1, 5, 0, 11, 10, 0, 1, 1, 3, 0,
	1, 1, 1, 0, 1, 3, 4, 7, 0, 5,
	0, 2, 8, 0, 9, 0, 8, 0, 6, 1,
	1, 3, 1, 0, 3, 6, 4, 0, 3, 4,
	1, 1, 2, 2, 5, 3, 4, 2, 1, 1,
	1, 1, 1, 2, 2, 2, 4, 2, 1, 1,
	3, 1, 4, 4, 2, 4, 1, 1, 0, 6,
	5, 0, 3, 0, 2, 0, 1, 1, 2, 1,
	1, 2, 1, 1, 3, 1, 1, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 2, 1, 2, 1, 1, 0, 1, 1, 3,
	1, 1, 2, 2, 1, 1, 1, 1, 1, 1,
	2, 3, 0, 1, 3, 2, 5, 4, 1, 1,
	3, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -49, -1, -50, -3, -2, -51, 53, 54, -6,
	-4, -25, 29, 24, 39, 38, 52, 51, -27, -31,
	-5, -41, -47, -48, 13, 18, 27, 30, 28, -34,
	-36, 55, 59, 61, -33, -35, 7, 8, -2, -51,
	-1, -28, -29, -30, 5, 4, -37, -38, 72, -39,
	-40, 75, 76, -16, -11, -13, 72, 25, -20, 51,
	-21, -18, 34, 33, 66, 65, 46, 47, 50, 48,
	-27, 35, 74, -26, 9, 52, -16, -17, 72, 34,
	9, -27, -11, 19, -11, -11, -2, 11, 36, 10,
	-43, -44, -45, -5, -31, -3, -41, -47, -43, -33,
	72, -9, -3, 75, 76, 41, -10, -16, -40, 9,
	-11, 65, 66, 67, 68, 69, 63, 64, 41, 44,
	45, 40, 42, 43, -10, -11, -27, -56, 75, -11,
	-11, 9, 72, 72, 76, 72, -17, 72, -11, 14,
	9, 21, 22, 31, -24, 9, 9, 9, -42, -45,
	-29, 60, 34, 9, -11, -11, 73, -32, 6, 72,
	77, -11, -11, -11, -11, -11, -11, -11, -11, -11,
	-11, -11, -11, -11, 73, -26, 72, -10, -11, -11,
	-10, -11, 73, -2, 20, -11, -55, -57, -12, -32,
	49, 72, 72, -46, 56, 57, 73, 72, 77, -39,
	-16, -10, -10, 73, -32, 77, 73, 73, -7, 15,
	-19, -18, -20, 72, -21, 22, -2, -2, -29, 9,
	-14, -15, 9, 26, -14, 58, -43, -43, -10, 73,
	73, -11, -8, 16, -11, 22, -20, -54, 23, 32,
	73, -32, 41, 9, 73, 73, -32, 17, -2, 14,
	-53, 73, -2, -12, -15, -13, -12, -11, -2, -2,
	23, -52, -22, -23, 11, 73, -7, 23, -22, -2,
	11, -24, -2, 12, -24, -29, 37, -29,
}

var yyDef = [...]int16{
	-2, -2, -2, -2, 27, 0, 4, 53, 57, 68,
	69, 70, 71, 72, 126, 126, 0, 0, 78, 6,
	7, 8, 9, 10, 0, 0, 0, 25, 148, 0,
	0, -2, -2, 105, -2, 18, 11, 0, 3, 5,
	26, 29, 31, 32, 151, 152, 0, 67, 126, 60,
	61, 0, 0, 73, 127, 106, 126, 0, 122, 0,
	124, 125, 130, 131, 0, 0, 134, 135, 136, 137,
	138, 0, 0, 79, 81, 0, 74, 75, 0, 86,
	87, 77, 0, 0, 0, 0, 0, 0, 0, 0,
	91, -2, 97, 99, 100, 0, 102, 103, 0, 16,
	0, 28, 30, 0, 0, 0, 0, 128, 62, 63,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 121, 123, 0, 154, 132,
	133, 145, 126, 0, 0, 126, 84, 0, 0, 25,
	0, 0, 47, 88, 19, 149, 0, 0, 93, 98,
	101, 104, 0, 54, 0, 66, 58, 126, 153, 126,
	65, 108, 109, 110, 111, 112, 113, 114, 115, 116,
	117, 118, 119, 120, 107, 80, 126, 0, 0, 0,
	0, 0, 76, 38, 0, 0, 25, 25, 0, 0,
	20, 142, 142, 0, -2, -2, 12, 126, 56, 59,
	129, 0, 0, 147, 0, 83, 82, 85, 40, 0,
	0, 49, 50, 0, 52, 45, 0, 0, 21, 150,
	0, 143, 139, 0, 0, 90, 92, 94, 0, 64,
	146, 0, 0, 25, 0, 43, 0, 25, 48, 89,
	19, 0, 0, 140, 19, 55, 0, 37, 41, 25,
	25, 51, 0, 22, 144, 141, 33, 0, 38, 0,
	46, 33, 25, 34, 0, 42, 39, 44, 25, 0,
	0, 0, 0, 24, 0, 35, 23, 36,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 69, 3, 3,
	72, 73, 67, 65, 6, 66, 75, 68, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 5,
	64, 3, 63, 74, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 76, 3, 77,
}

var yyTok2 = [...]int8{
	2, 3, 7, 8, 9, 10, 11, 12, 13, 14,
	15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
	35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
	45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
	55, 56, 57, 58, 59, 60, 61, 62, 70, 71,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:104
		{
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:105
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].body, yylex)
			}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:110
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[2].opt_body, yylex)
			}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:120
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].global_variables, yylex)
			}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:125
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].funcProc, yylex)
			}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:130
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].preproc_if, yylex)
			}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:135
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].region_stmt, yylex)
			}
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:140
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].use_stmt, yylex)
			}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:149
		{
			yyVAL.directive = &DirectiveStatement{Name: yyDollar[1].token.literal}
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:150
		{
			yyVAL.directive = &DirectiveStatement{Name: yyDollar[1].token.literal, Src: yyDollar[3].token.literal}
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:153
		{
			yyVAL.directive = nil
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:154
		{
			yyVAL.directive = yyDollar[1].directive
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:157
		{
			yyVAL.directives = []*DirectiveStatement{yyDollar[1].directive}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:158
		{
			yyVAL.directives = append(yyVAL.directives, yyDollar[2].directive)
		}
	case 17:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:161
		{
			yyVAL.directives = nil
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:162
		{
			yyVAL.directives = yyDollar[1].directives
		}
	case 19:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:165
		{
			yyVAL.opt_export = nil
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:166
		{
			yyVAL.opt_export = &yyDollar[1].token
		}
	case 21:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:169
		{
			yyVAL.global_variables = make([]GlobalVariables, len(yyDollar[3].identifiers), len(yyDollar[3].identifiers))
			for i, v := range yyDollar[3].identifiers {
				if yyDollar[1].directive != nil {
					yyVAL.global_variables[i].Directive = yyDollar[1].directive
				}

				yyVAL.global_variables[i].Export = yyDollar[4].opt_export != nil
				yyVAL.global_variables[i].Var = VarStatement{Name: v.literal}
			}
		}
	case 22:
		yyDollar = yyS[yypt-7 : yypt+1]
//line ast/grammar.y:182
		{
			isFunction(true, yylex)
		}
	case 23:
		yyDollar = yyS[yypt-11 : yypt+1]
//line ast/grammar.y:183
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeFunction, yyDollar[1].directives, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[9].opt_explicit_variables, yyDollar[10].opt_body)
			isFunction(false, yylex)
		}
	case 24:
		yyDollar = yyS[yypt-10 : yypt+1]
//line ast/grammar.y:188
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeProcedure, yyDollar[1].directives, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[8].opt_explicit_variables, yyDollar[9].opt_body)
		}
	case 25:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:193
		{
			yyVAL.opt_body = nil
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:194
		{
			yyVAL.opt_body = yyDollar[1].body
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:198
		{
			yyVAL.body = Statements{yyDollar[1].stmt}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:199
		{
			if yyDollar[2].token.literal == ":" && len(yyDollar[1].opt_body) > 0 {
				if _, ok := yyDollar[1].opt_body[len(yyDollar[1].opt_body)-1].(*GoToLabelStatement); !ok {
					yylex.Error("semicolon (;) is expected")
				}
			}
			if yyDollar[3].stmt != nil {
				yyVAL.body = append(yyVAL.body, yyDollar[3].stmt)
			}
		}
	case 29:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:212
		{
			yyVAL.stmt = nil
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:213
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:216
		{
			yyVAL.token = yyDollar[1].token
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:216
		{
			yyVAL.token = yyDollar[1].token
		}
	case 33:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:220
		{
			yyVAL.opt_explicit_variables = map[string]VarStatement{}
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:221
		{
			yyVAL.opt_explicit_variables = yyDollar[1].explicit_variables
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:224
		{
			if vars, err := appendVarStatements(map[string]VarStatement{}, yyDollar[2].identifiers); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.explicit_variables = vars
			}
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:231
		{
			if vars, err := appendVarStatements(yyDollar[1].explicit_variables, yyDollar[3].identifiers); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.explicit_variables = vars
			}
		}
	case 37:
		yyDollar = yyS[yypt-7 : yypt+1]
//line ast/grammar.y:242
		{
			yyVAL.stmt_if = &IfStatement{
				Expression:  yyDollar[2].stmt,
				TrueBlock:   yyDollar[4].opt_body,
				IfElseBlock: yyDollar[5].opt_elseif_list,
				ElseBlock:   yyDollar[6].opt_else,
			}
		}
	case 38:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:252
		{
			yyVAL.opt_elseif_list = Statements{}
		}
	case 39:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:253
		{
			yyVAL.opt_elseif_list = append(yyDollar[5].opt_elseif_list, &IfStatement{
				Expression: yyDollar[2].stmt,
				TrueBlock:  yyDollar[4].opt_body,
			})
		}
	case 40:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:261
		{
			yyVAL.opt_else = nil
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:262
		{
			yyVAL.opt_else = yyDollar[2].opt_body
		}
	case 42:
		yyDollar = yyS[yypt-8 : yypt+1]
//line ast/grammar.y:265
		{
			yyVAL.stmt = TernaryStatement{
				Expression: yyDollar[3].stmt,
				TrueBlock:  yyDollar[5].stmt,
				ElseBlock:  yyDollar[7].stmt,
			}
		}
	case 43:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ast/grammar.y:274
		{
			setLoopFlag(true, yylex)
		}
	case 44:
		yyDollar = yyS[yypt-9 : yypt+1]
//line ast/grammar.y:274
		{
			yyVAL.stmt_loop = &LoopStatement{
				For:  yyDollar[3].token.literal,
				In:   yyDollar[5].stmt,
				Body: yyDollar[8].opt_body,
			}
			setLoopFlag(false, yylex)
		}
	case 45:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:282
		{
			setLoopFlag(true, yylex)
		}
	case 46:
		yyDollar = yyS[yypt-8 : yypt+1]
//line ast/grammar.y:282
		{
			yyVAL.stmt_loop = &LoopStatement{
				For:  yyDollar[2].stmt,
				To:   yyDollar[4].stmt,
				Body: yyDollar[7].opt_body,
			}
			setLoopFlag(false, yylex)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:290
		{
			setLoopFlag(true, yylex)
		}
	case 48:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ast/grammar.y:290
		{
			yyVAL.stmt_loop = &LoopStatement{
				WhileExpr: yyDollar[2].stmt,
				Body:      yyDollar[5].opt_body,
			}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:299
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:300
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:301
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:302
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 53:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:311
		{
			yyVAL.stmt = nil
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:312
		{
			prop := VarStatement{Name: yyDollar[3].token.literal}
			if yyDollar[1].stmt != nil {
				yyVAL.stmt = CallChainStatement{Unit: prop, Call: yyDollar[1].stmt}
			} else {
				yyVAL.stmt = prop
			}
		}
	case 55:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ast/grammar.y:320
		{
			method := MethodStatement{Name: yyDollar[3].token.literal, Param: yyDollar[5].exprs}
			if yyDollar[1].stmt != nil {
				yyVAL.stmt = CallChainStatement{Unit: method, Call: yyDollar[1].stmt}
			} else {
				yyVAL.stmt = method
			}
		}
	case 56:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:328
		{
			if yyDollar[1].stmt != nil {
				yyVAL.stmt = ItemStatement{Object: yyDollar[1].stmt, Item: yyDollar[3].stmt}
			} else {
				yyVAL.stmt = ItemStatement{Object: nil, Item: yyDollar[3].stmt}
			}
		}
	case 57:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:341
		{
			yyVAL.stmt = nil
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:342
		{
			// Foo() — вызов метода
			yyVAL.stmt = MethodStatement{Name: "", Param: yyDollar[2].exprs}
		}
	case 59:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:346
		{
			// Foo().Bar... — вызов с продолжением
			method := MethodStatement{Name: "", Param: yyDollar[2].exprs}
			yyVAL.stmt = CallChainStatement{Unit: yyDollar[4].stmt, Call: method}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:351
		{
			// .свойство, .Метод(), [индекс] или их цепочка
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:360
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:361
		{
			yyVAL.stmt = CallChainStatement{Unit: yyDollar[2].stmt, Call: yyDollar[1].stmt}
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:366
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[2].token.literal}
		}
	case 64:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:369
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[2].token.literal, Param: yyDollar[4].exprs}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:372
		{
			yyVAL.stmt = ItemStatement{Object: nil, Item: yyDollar[2].stmt}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:382
		{
			// Присваивание: а = 1, а.б = 1, а.Метод().в = 1
			lhs := VarStatement{Name: yyDollar[1].token.literal}
			if yyDollar[2].stmt != nil {
				yyVAL.stmt = AssignmentStatement{Var: CallChainStatement{Unit: yyDollar[2].stmt, Call: lhs}, Expr: ExprStatements{Statements: Statements{yyDollar[4].stmt}}}
			} else {
				yyVAL.stmt = AssignmentStatement{Var: lhs, Expr: ExprStatements{Statements: Statements{yyDollar[4].stmt}}}
			}
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:391
		{
			// Вызов как statement: Foo(), а.Метод(), а.б
			if yyDollar[2].stmt == nil {
				// Голый идентификатор: а;
				yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
			} else if method, ok := yyDollar[2].stmt.(MethodStatement); ok && method.Name == "" {
				// Простой вызов Foo() — НЕ оборачиваем в CallChainStatement
				method.Name = yyDollar[1].token.literal
				yyVAL.stmt = method
			} else {
				// Цепочка: а.Метод(), а.б, а[0]
				base := VarStatement{Name: yyDollar[1].token.literal}
				yyVAL.stmt = CallChainStatement{Unit: yyDollar[2].stmt, Call: base}
			}
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:406
		{
			yyVAL.stmt = yyDollar[1].stmt_if
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:407
		{
			yyVAL.stmt = yyDollar[1].stmt_loop
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:408
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:409
		{
			yyVAL.stmt = ContinueStatement{}
			checkLoopOperator(yyDollar[1].token, yylex)
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:410
		{
			yyVAL.stmt = BreakStatement{}
			checkLoopOperator(yyDollar[1].token, yylex)
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:411
		{
			yyVAL.stmt = ThrowStatement{Param: yyDollar[2].stmt}
			checkThrowParam(yyDollar[1].token, yyDollar[2].stmt, yylex)
		}
	case 74:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:412
		{
			yyVAL.stmt = &ReturnStatement{Param: yyDollar[2].stmt}
			checkReturnParam(yyDollar[2].stmt, yylex)
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:413
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[2].stmt}}}
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:414
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[3].stmt}}}
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:415
		{
			yyVAL.stmt = GoToStatement{Label: yyDollar[2].goToLabel}
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:416
		{
			yyVAL.stmt = yyDollar[1].goToLabel
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:421
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:422
		{
			yyVAL.stmt = CallChainStatement{Unit: yyDollar[3].stmt, Call: yyDollar[1].stmt}
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:428
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:429
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: yyDollar[3].exprs}
		}
	case 83:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:430
		{
			yyVAL.stmt = ItemStatement{Object: yyDollar[1].stmt, Item: yyDollar[3].stmt}
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:431
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[2].stmt}}}
		}
	case 85:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:432
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[3].stmt}}}
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:435
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:436
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:439
		{
			setTryFlag(true, yylex)
		}
	case 89:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ast/grammar.y:439
		{
			yyVAL.stmt = TryStatement{Body: yyDollar[2].opt_body, Catch: yyDollar[5].opt_body}
			setTryFlag(false, yylex)
		}
	case 90:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:444
		{
			yyVAL.preproc_if = &PreprocessorIfStatement{
				Condition: yyDollar[1].token.literal,
				ThenBlock: yyDollar[2].preproc_body,
				ElseIfs:   yyDollar[3].preproc_elseifs,
				ElseBlock: yyDollar[4].preproc_body,
			}
		}
	case 91:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:453
		{
			yyVAL.preproc_elseifs = nil
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:454
		{
			yyVAL.preproc_elseifs = append(yyDollar[1].preproc_elseifs, PreprocessorElseIf{Condition: yyDollar[2].token.literal, Block: yyDollar[3].preproc_body})
		}
	case 93:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:459
		{
			yyVAL.preproc_body = nil
		}
	case 94:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:460
		{
			yyVAL.preproc_body = yyDollar[2].preproc_body
		}
	case 95:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:463
		{
			yyVAL.preproc_body = nil
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:464
		{
			yyVAL.preproc_body = yyDollar[1].preproc_body
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:467
		{
			yyVAL.preproc_body = yyDollar[1].preproc_body
		}
	case 98:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:468
		{
			yyVAL.preproc_body = append(yyDollar[1].preproc_body, yyDollar[2].preproc_body...)
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:471
		{
			yyVAL.preproc_body = Statements{yyDollar[1].funcProc}
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:472
		{
			stmts := make(Statements, len(yyDollar[1].global_variables))
			for i, gv := range yyDollar[1].global_variables {
				stmts[i] = gv
			}
			yyVAL.preproc_body = stmts
		}
	case 101:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:479
		{
			yyVAL.preproc_body = Statements{yyDollar[1].stmt}
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:480
		{
			yyVAL.preproc_body = Statements{yyDollar[1].preproc_if}
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:481
		{
			yyVAL.preproc_body = Statements{yyDollar[1].region_stmt}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:484
		{
			yyVAL.region_stmt = &RegionStatement{
				Name: yyDollar[1].token.literal,
				Body: yyDollar[2].preproc_body,
			}
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:491
		{
			yyVAL.use_stmt = &UseStatement{
				Path: yyDollar[1].token.literal,
			}
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:498
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:499
		{
			yyVAL.stmt = yyDollar[2].exprs
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:500
		{
			yyVAL.stmt = &ExpStatement{Operation: OpPlus, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 109:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:501
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMinus, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:502
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMul, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:503
		{
			yyVAL.stmt = &ExpStatement{Operation: OpDiv, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:504
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMod, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 113:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:505
		{
			yyVAL.stmt = &ExpStatement{Operation: OpGt, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:506
		{
			yyVAL.stmt = &ExpStatement{Operation: OpLt, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:507
		{
			yyVAL.stmt = &ExpStatement{Operation: OpEq, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:508
		{
			yyVAL.stmt = &ExpStatement{Operation: OpOr, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:509
		{
			yyVAL.stmt = &ExpStatement{Operation: OpAnd, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:510
		{
			yyVAL.stmt = &ExpStatement{Operation: OpNe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:511
		{
			yyVAL.stmt = &ExpStatement{Operation: OpLe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:512
		{
			yyVAL.stmt = &ExpStatement{Operation: OpGe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 121:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:513
		{
			yyVAL.stmt = not(yyDollar[2].stmt)
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:514
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 123:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:515
		{
			yyVAL.stmt = GoToStatement{Label: yyDollar[2].goToLabel}
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:516
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:517
		{
			if tok, ok := yyDollar[1].stmt.(Token); ok {
				yyVAL.stmt = tok.literal
			} else {
				yyVAL.stmt = yyDollar[1].stmt
			}
		}
	case 126:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:526
		{
			yyVAL.stmt = nil
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:526
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:528
		{
			yyVAL.exprs = ExprStatements{Statements: Statements{yyDollar[1].stmt}}
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:529
		{
			yyVAL.exprs.Statements = append(yyVAL.exprs.Statements, yyDollar[3].stmt)
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:532
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:533
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 132:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:534
		{
			yyVAL.stmt = unaryMinus(yyDollar[2].stmt)
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:535
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:536
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:537
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:538
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:539
		{
			yyVAL.stmt = UndefinedStatement{}
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:540
		{
			yyVAL.stmt = yyDollar[1].goToLabel
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:544
		{
			yyVAL.declarations_method_param = *(&ParamStatement{}).Fill(nil, yyDollar[1].token)
		}
	case 140:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:545
		{
			yyVAL.declarations_method_param = *(&ParamStatement{}).Fill(&yyDollar[1].token, yyDollar[2].token)
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:546
		{
			yyVAL.declarations_method_param = *(yyVAL.declarations_method_param.DefaultValue(yyDollar[3].stmt))
		}
	case 142:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ast/grammar.y:549
		{
			yyVAL.declarations_method_params = []ParamStatement{}
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:550
		{
			yyVAL.declarations_method_params = []ParamStatement{yyDollar[1].declarations_method_param}
		}
	case 144:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:551
		{
			yyVAL.declarations_method_params = append(yyDollar[1].declarations_method_params, yyDollar[3].declarations_method_param)
		}
	case 145:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ast/grammar.y:559
		{
			yyVAL.stmt = NewObjectStatement{Constructor: yyDollar[2].token.literal}
		}
	case 146:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ast/grammar.y:560
		{
			yyVAL.stmt = NewObjectStatement{Constructor: yyDollar[2].token.literal, Param: yyDollar[4].exprs}
		}
	case 147:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ast/grammar.y:561
		{
			yyVAL.stmt = NewObjectStatement{Param: yyDollar[3].exprs}
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:566
		{
			yyVAL.goToLabel = &GoToLabelStatement{Name: yyDollar[1].token.literal}
		}
	case 149:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:568
		{
			yyVAL.identifiers = []Token{yyDollar[1].token}
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ast/grammar.y:569
		{
			yyVAL.identifiers = append(yyVAL.identifiers, yyDollar[3].token)
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:572
		{
			yyVAL.token = yyDollar[1].token
		}
	case 152:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:573
		{
			yyVAL.token = yyDollar[1].token
		}
	case 153:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ast/grammar.y:574
		{
			yyVAL.token = yyDollar[1].token
		}
	}
	goto yystack /* stack new state and value */
}
